### ISSUE TITLE
Create Pull Request with applied fixes not working

### ISSUE THREAD

**Issue by raghu1515** [oxsecurity/megalinter#1542]
As suggested in workflow, I am using the if condition to Create Pull Request with applied fixes:

```yaml
if: steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) && !contains(github.event.head_commit.message, 'skip fix')
```

But Create Pull Request with applied fixes is not working.  Please help.

![image](https://user-images.githubusercontent.com/100363529/175067663-99d9aeca-2a30-453e-9ac5-b51f14318938.png)

**Comment by raghu1515** [comment]
Please correct me if I am wrong. My understanding on IF condition:
output has updated sources == 1 (meaning minimum one source file in the output to update with Pull request OR "TRUE") 
AND
APPLY_FIXES_EVENT == 'all' 
OR 
APPLY_FIXES_EVENT == github.event_name 
AND
APPLY_FIXES_MODE == 'pull_request' 
AND
github.event_name == 'push' 
OR 
github.event.pull_request.head.repo.full_name == github.repository 
AND
github.event.head_commit.message DOES NOT CONTAIN 'skip fix'

Usually if any condition is satisfied, the output will be 0 and not 1, so I am lingering whether the first condition should be zero?

**Comment by Kurt-von-Laven** [comment]
Sorry, but I cannot follow the logic without parentheses. You can use [triple back ticks to format a fenced code block in GFM](https://github.github.com/gfm/#fenced-code-blocks).

**Comment by estahn** [comment]
I have the same issue and I'm wondering if anyone has ever tested the action 🤔 . I added the following step after the cleanup step – which btw is not executed because it doesn't have `if: always()`:

```
      - name: debug
        if: always()
        run: |
          echo "steps.ml.outputs.has_updated_sources ${{steps.ml.outputs.has_updated_sources}}"
          echo "env.APPLY_FIXES_EVENT ${{env.APPLY_FIXES_EVENT}}"
          echo "github.event_name ${{github.event_name}}"
          echo "env.APPLY_FIXES_MODE ${{env.APPLY_FIXES_MODE}}"
          echo "github.event.pull_request.head.repo.full_name ${{github.event.pull_request.head.repo.full_name}}"
          echo "github.repository ${{github.repository}}"
```

Given the output, the condition is `true` and the step should have been executed. It wasn't. It's being skipped.

What I've done is adding `${{ success() }} || ${{ failure() }}` to the expression, which then becomes:

```
if: (${{ success() }} || ${{ failure() }}) && steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
``` 

Now I'm facing another issue:
```
  Working base is commit '9695c32abf00be05b98881abbbea2b1b25858c6f'
  Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied.
```

Continue debugging, but I think the action is not in a workable state.

**Comment by Kurt-von-Laven** [comment]
[Many projects actively use the GitHub Action](https://github.com/megalinter/megalinter/network/dependents?package_id=UGFja2FnZS0yOTQyNTYxNDY1), but I think you're probably right about the cleanup step missing `if: always()`, and I certainly don't claim there are no bugs. Please feel free to open a pull request with the caveat that MegaLinter is currently frozen for another week or so in order to focus on getting v6 out the door, so it won't be reviewed immediately.

Would you be able to share the output from your debug step? I'm a little in the dark here as my team doesn't run MegaLinter via the GitHub Action. Are you running the workflow on tag pushes by chance (c.f., peter-evans/create-pull-request#707)?

**Comment by estahn** [comment]
Apologies, I think the comment sounds pretty harsh.

The output of the debug step just confirms that the condition should have been `true` and therefore run. I assume GitHub Actions fails all subsequent steps after a failing step and only if you add `always`, `success` or `failure` this will be taken as an exception. I couldn't find supporting documentation in the GitHub Actions docs but that is how it behaves.

Btw my code contains a bug, it should be:
```
if: (success() || failure()) && steps.ml.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE == 'pull_request' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
```

I suppose you could replace `(success() || failure())` with `always()` but I haven't tried that.

I'm running the workflow on a regular push to a pull request.

**Comment by Kurt-von-Laven** [comment]
It's all good. Your assumption that [`if: success()` is the default](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions) is correct. [`always()`](https://docs.github.com/en/actions/learn-github-actions/expressions#always) is equivalent to `success() || failure() || cancelled()`. In case anyone following along is confused, none of that has anything to do with MegaLinter or [its accompanying GitHub Action](https://github.com/megalinter/megalinter/blob/main/action.yml), which doesn't even call [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request). I'm guessing you're copying some subset of [this non-callable workflow](https://github.com/megalinter/megalinter/blob/3af8854caeb74348e29c9dec2e633e4da6db5d05/.github/workflows/mega-linter.yml) but with a step that's failing before create-pull-request is run. Non-callable workflows generally aren't intended for use by other projects, although we are always happy to learn how they can be improved.

It sounds like the other issue you are hitting also has nothing to do with MegaLinter, but rather the aforementioned create-pull-request action.

**Comment by estahn** [comment]
Yes, you are correct. None of this is directly a MegaLinter issue. The entire ticket is about this non-callable workflow, as you call it.

I'm a bit confused by this statement:
> Non-callable workflows generally aren't intended for use by other projects 

When running `npx mega-linter-runner --install` this non-callable workflow will be created. Why would it be created if its not intended to be used by other projects 🤔 

I was using it as is and didn't make any adjustments. Now I did, because of the issues described above.

**Comment by Kurt-von-Laven** [comment]
It’s probably purely a matter of my own ignorance as I wasn’t aware of the existence of `--install`. If you got it working, it sounds like we should incorporate your changes though if you are interested in opening a pull request.

**Comment by estahn** [comment]
Will open up a pull request. It's 1am, so I will catch some 💤

**Comment by nvuillam** [comment]
@estahn do you still have the issue ?

**Comment by nvuillam** [comment]
Note: some people succeed, but maybe they had to tweak the workflow

https://github.com/search?q=%5BApply+MegaLinter+fixes%5D&type=commits

It also works better with PAT defined, else after the new commit, the Github Actions Workflows are not run again -> https://oxsecurity.github.io/megalinter/latest/configuration/#apply-fixes
