### ISSUE TITLE
DISABLE_LINTERS not working as expected when running locally

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [oxsecurity/megalinter#1659]
**Describe the bug**
DISABLE_LINTERS not working as expected when running locally

**To Reproduce**
```
npx mega-linter-runner --flavor python -e 'DISABLE_LINTERS=PYTHON_BANDIT,PYTHON_PYLINT,PYTHON_MYPY,REPOSITORY_SEMGREP,SPELL_CSPELL'
```
Only bandit is skipped, the other linters remain

**Expected behavior**
All specified linters should be disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/95432492/181268385-3f649aec-5a6f-40ee-a131-c77b66ccbaf3.png)

![image](https://user-images.githubusercontent.com/95432492/181269126-98820993-fa51-4eb9-899e-474826b54696.png)

**Additional context**
Using Mac M1

**Comment by Kurt-von-Laven** [comment]
I have encountered a similar issue before. My instinct is to try adding an extra set of double quotes around the single quotes on account of “Warning: Quotes are mandatory” ~ https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/

Please let me know if that doesn’t resolve this issue for you.

**Comment by SoumayaMauthoorMOJ** [comment]
Hey @Kurt-von-Laven I'm using a Mac M1 so I'll wait for https://github.com/oxsecurity/megalinter/pull/1553 to merge to try this. Will close in the meanwhile.

**Comment by Kurt-von-Laven** [comment]
I don’t think the two issues are related actually, but I can see the rationale for waiting in any case.

**Comment by echoix** [comment]
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/95432492/181268385-3f649aec-5a6f-40ee-a131-c77b66ccbaf3.png)

If you look here, at the 9th line, starting with "`Command: docker run -v`", you see the problem: the interpreted command argument starts by `-e DISABLE_LINTERS=PYTHON_BANDIT`, where `-e` means to set an environment variable, `DISABLE_LINTERS` is the environment variable name, and `PYTHON_BANDIT` is the environment's variable value. However, the rest is interpreted as `-e PYTHON_PYLINT` `-e PYTHON_MYPY` etc. So the list is not interpreted as the value of DISABLE_LINTERS.

I tested on windows (PowerShell) and had the same problem. I tried different combinations of quoting, but always got the problem. I think I located the problem, that is in the mega-linter-runner.

Look at lines: https://github.com/oxsecurity/megalinter/blob/e88ab3e9adf6d08526b178435583bc0c268f8246/mega-linter-runner/lib/runner.js#L138-L142

This would work correctly for forwarding all env variables types to docker, but the optionator package seems to be pretty strict about splitting at commas. I couldn't find a way for it to not split the array to include what we want.

For example: 
![image](https://user-images.githubusercontent.com/27212526/181648380-84dbe7f8-38cf-447f-984b-6869e420302b.png)
Here I just placed the options processing code above the docker socket test since I was using a dev container. We see that opetions.env is already parsed incorrectly before the `if (options.env) {` lien is called. 

I couldn't find a way to have the optionator to do what we want, nor have the underlying [lenv](https://github.com/gkz/levn) or [type-check](https://github.com/gkz/type-check) to describe what a environment variable option string could look like.

Seeing when everything was changed, I strongly think that this code, setting the env variable with the mega-linter-runner --env option, never worked since at least two years. Another strategy needs to be thought about.
I see that repeating the `DISABLE_LINTERS=` after each comma makes the docker run command to have all segments in the run command, but I didn't verify how a container handles having multiple times the same env variable set with different values. Are they combined or only the last one is kept?

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @echoix! I'm surprised that the env option has not worked in a while. Don't people tend to run the megalinter locally (as well as though CI pipeline)? I'm asking from a best practice perspective because I'm supposed to share this with my team

**Comment by echoix** [comment]
Someone correct me if I'm wrong, but I think that running locally still uses the megalinter yaml config file, and the disabled linters can be set there. That's why I think it hasn't been caught yet. This could be a good test case. The syntax of the examples are correct if we are feeding it to Docker, but here we are passing it to optionator, which doesn't work as expected.

**Comment by nvuillam** [comment]
@echoix I confirm that using mega-linter-runner still uses local .mega-linter.yml file :)
If variables are defined in both ENV vars and .mega-linter.yml, the priority is on ENV vars

@SoumayaMauthoorMOJ Did you try `npx mega-linter-runner --flavor python -e 'DISABLE_LINTERS="PYTHON_BANDIT,PYTHON_PYLINT,PYTHON_MYPY,REPOSITORY_SEMGREP,SPELL_CSPELL"'` ?

**Comment by Kurt-von-Laven** [comment]
As far as I know our team [pioneered](#1438) [running MegaLinter as a pre-commit hook](https://oxsecurity.github.io/megalinter/latest/mega-linter-runner/#pre-commit-hook) and [reusing the pre-commit hooks as a CI pipeline](https://github.com/ScribeMD/pre-commit-action) in April 2022, although there were definitely folks doing each of these things separately before us (and possibly some who had both working but didn't share ha ha). After a few previous iterations, we have loved our current toolchain, and I see us sticking with it for the foreseeable future. I infer from the questions that crop up in the issue tracker that at least some other teams have since taken a similar approach, which is exciting to see. I am confident the `DISABLE_LINTERS` environment variable has worked at least since April 2022 since [we rely on it](https://github.com/ScribeMD/slack-templates/blob/2e958beb4abdc05b33773af982863c771636c2af/.pre-commit-config.yaml#L29-L30), and it behaves as expected. It did take me several iterations to get the quoting right, so I feel everyone's pain there. We would gladly accept a pull request to improve the documentation.

**Comment by echoix** [comment]
> @SoumayaMauthoorMOJ Did you try `npx mega-linter-runner --flavor python -e 'DISABLE_LINTERS="PYTHON_BANDIT,PYTHON_PYLINT,PYTHON_MYPY,REPOSITORY_SEMGREP,SPELL_CSPELL"'` ?
> 

I obviously tried it myself on Thursday, and any other variations I already saw and that I could think of, before going down a layer down until suspecting the library used. Next step to make absolutely sure would be to dive into the library to see if the "array" detection is simply a naïve split on comma. I tried adding braces, squared brackets, all escaping I could think of. Overall, the fact that we use it as an ENV variable doesn't matter to the option processing. The equals is simply another character in the string. It will split at the comma no matter what. But at least, the "array" is a real array with merged items if we use multiple times `-e`, `--env`, or a mix of both.

**Comment by Kurt-von-Laven** [comment]
@echoix, again though, we have been successfully using the `DISABLE_LINTERS` environment variable for months. Pasting in the relevant excerpt from the working example I linked to previously:

`"'DISABLE_LINTERS=COPYPASTE_JSCPD,GRAPHQL_GRAPHQL_SCHEMA_LINTER'"`

It's possible there is some funny business going on that makes copying this syntax verbatim from YAML to the shell not work. My guess would be that YAML and the shell both consume the outermost quotes though, so hopefully copying verbatim does work?

**Comment by echoix** [comment]
Here's the gotcha: using the `-e` in mega-linter-runner isn't really the same as having an environnement variable set. It is providing an argument (optionator format), of type array of strings `[String]` (processed by levn)(which uses type-checker).

The syntax for en environnement variable and the syntax to send to docker is correct. But the thing is the parsing done for the command line options in the node.js application does not copy verbatim the argument passed. It processes this string with its conventions for how to handle arrays.

**Comment by Kurt-von-Laven** [comment]
I seem to recall reaching a similar conclusion when analyzing the code upon initially experiencing the symptom reported by the OP. I was surprised to find that it worked with the extra quotes, and I confess that I immediately stopped trying to understand why it worked at that point. Lest anyone get confused, we used `--env` (a.k.a., `-e`) as opposed to setting an environment variable.

**Comment by SoumayaMauthoorMOJ** [comment]
All good! Based on [link](https://github.com/ScribeMD/slack-templates/blob/2e958beb4abdc05b33773af982863c771636c2af/.pre-commit-config.yaml#L29-L30) from @Kurt-von-Laven:

`npx mega-linter-runner --flavor python -e "'DISABLE_LINTERS=PYTHON_BANDIT,PYTHON_PYLINT,PYTHON_MYPY,REPOSITORY_SEMGREP,SPELL_CSPELL'"`

![image](https://user-images.githubusercontent.com/95432492/182039405-88202e93-714c-4a25-b6fe-b9b06479deaf.png)

To be honest I hadn't realised that running locally still uses the megalinter yaml config file, so that was good enough for me, but thought it would be good to test just in case :-) 

Will raise documentation PR.

Once again thanks for the prompt feedback from everyone appreciate it 👍

**Comment by pessi-v** [comment]
It appears, that only the last -e option for any env variable will be used, so if you want to disable multiple linters, you'd have to use

-e "'DISABLE_LINTERS=SPELL_CSPELL,SPELL_MISSPELL'"


 _not_

-e "'DISABLE_LINTERS=SPELL_CSPELL'" -e "'DISABLE_LINTERS=SPELL_MISSPELL'"

**Comment by echoix** [comment]
When you say locally, you're talking about docker or mega-linter-runner?
