### ISSUE TITLE
Enhance performances by grouping linters only when they can fix sources

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#1785]
- Performances improvements: when running linters in parallel, run in the same process only the linters from same descriptor and that can update the same sources (to avoid concurrency). Other linters can be run independently.

**Comment by Kurt-von-Laven** [comment]
Does this mean it's now possible for one linter to modifying files while another linter that doesn't make modifications is linting the same files?

**Comment by nvuillam** [comment]
Yes it is :)
I don't see cases where it could create problems, as modifying linters are run before non-modifying ones
But non-modifying ones do not wait that modifying ones are completed... I could implement that but it would reduce performances... do you think it's ok that we wait for wrong feedbacks ?

**Comment by Kurt-von-Laven** [comment]
It seems preferable to lint the files after they have reached their final state since one run that is a bit slower is still a lot faster than two runs, and most linters sensibly output line numbers to go with their error messages that can easily be thrown off by the sorts of formatting fixes Prettier and Black do, for example. When we first set up MegaLinter, we had to tweak some linter settings to keep them from fighting with one another, and sorting those conflicts out without a predictable execution order would have been significantly more painful. Our team specifically is unlikely to be impacted by these sorts of issues since we are now aware of the possibility, but I could see it causing some grief for newcomers especially. In the meantime we will just enjoy the faster performance!
