### ISSUE TITLE
v8r failing due to megalinter not executing within project path

### ISSUE THREAD

**Issue by estahn** [oxsecurity/megalinter#1875]
**Describe the bug**

I created a file `.github/workflows/deploy.yml`. Running megalinter in GitHub Actions will produce an error as v8r detects a schema which is incorrect.

`v8r` uses the following schemastore file to detect the required schema (https://github.com/SchemaStore/schemastore/blob/2e3b50930f40c237d0070414701ea7c44ca2c85e/src/api/json/catalog.json#L1073-L1078). Within this file an attribute `fileMatch` will be used to detect the schema based on the file path. MegaLinter does not pass a relative path (it will pass `/github/workspace/.github/workflows/deploy.yml`) hence the match will match with the wrong result.

This may or may not be an issue with v8r, schemastore or megalinter. I'm open for suggestions where to place this.

**To Reproduce**

1. Create project dir and file called `mkdir -p v8r-test/.github/workflows && touch v8r-test/.github/workflows/deploy.yml`
2. Run v8r from within project dir `cd v8r-test && npx v8r@latest .github/workflows/deploy.yml --verbose`
3. Run v8r from outside the project dir `cd .. && npx v8r@latest .github/workflows/deploy.yml --verbose`
4. See different results

**Expected behavior**
Step 2 and 3 should behave the same.

**Comment by estahn** [comment]
I have tried `YAML_V8R_CLI_LINT_MODE: project` which fails with:
![image](https://user-images.githubusercontent.com/362174/190408348-8ea57150-407f-4880-8546-a058c1d16ef4.png)

**Comment by nvuillam** [comment]
Use of relative paths to call linters within MegaLinter is something inherited from Super-Linter , and that's not the first time it causes problems...

Someday i'll change all that so that all files are sent with relative path and with repo root as cwd ... but as it may require lots of impacts to be managed, I suggest than meanwhile you :

- force the use of the json schema within your yaml by adding in your yaml: `$schema: https://raw.githubusercontent.com/deployphp/deployer/master/src/schema.json`

and if it does not work, disable check on this file until there is a new version of MegaLinter with a fix:

- add `YAML_V8R_FILTER_REGEX_EXCLUDE: ` in your .mega-linter.yml file

**Comment by nvuillam** [comment]
It seems you can also define local schema catalog with v8r, so you could define one matching the file name and targetting the appropriate json schema url

https://github.com/chris48s/v8r#using-a-custom-catlog
