### ISSUE TITLE
The Auto-Update Linters workflow is not updating `actionlint`

### ISSUE THREAD

**Issue by parkerbxyz** [oxsecurity/megalinter#1925]
MegaLinter's version of `actionlint` ([v1.6.16](https://github.com/rhysd/actionlint/releases/tag/v1.6.16)) is a few releases behind. The latest release of `actionlint` as of this writing is [v1.6.20](https://github.com/rhysd/actionlint/releases/tag/v1.6.20).

Should the auto-update linters workflow be updating this?

**Comment by Kurt-von-Laven** [comment]
There are a number of issues like this that might be easiest to address by switching from Dependabot to the more fully featured Renovate.

**Comment by nvuillam** [comment]
@Kurt-von-Laven dependabot & renovate are quite cool, but there are so many linters... I don't want to spend all my evenings validating automated merge requests :D 

@parkerbxyz for some reason actionlint is downgraded to 1.6.16, I don't really remember why, it is generally because there is a breaking change in a new version, or even a broken new version... but we can probably arrange that :)

---> https://github.com/oxsecurity/megalinter/blob/88a858eca0d241a5611b234a1b331771bd5335f3/megalinter/descriptors/action.megalinter-descriptor.yml#L32

**Comment by Kurt-von-Laven** [comment]
[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit) and [Renovate](https://docs.renovatebot.com/configuration-options/#prconcurrentlimit) both have a setting that allows us to limit the number of open pull requests, so we can merge them at whatever pace we like (or even auto-merge them whenever they pass CI).

**Comment by nvuillam** [comment]
> [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit) and [Renovate](https://docs.renovatebot.com/configuration-options/#prconcurrentlimit) both have a setting that allows us to limit the number of open pull requests, so we can merge them at whatever pace we like (or even auto-merge them whenever they pass CI).

The problem is that both of them will update Dockerfile, not descriptor files ^^

**Comment by Kurt-von-Laven** [comment]
That's certainly a limitation of Dependabot, but my understanding is that Renovate is practically arbitrarily customizable?
