### ISSUE TITLE
Single/double quotes error in R

### ISSUE THREAD

**Issue by erossini** [oxsecurity/megalinter#1943]
I have an issue with `R` because Megalinter raises an error about single quote. In `R` you can use single or double quote interchangeable and this it is not a real error.

How can I fix ti or ignore this error?

Thank you in advance,
Enrico

**Comment by Kurt-von-Laven** [comment]
Assuming this is lintr that is complaining, I would refer to [its documentation](https://lintr.r-lib.org/) for how to configure particular issues to be ignored. Linting is not always meant to catch issues that are objectively right or wrong; the intention with this style rule is likely to encourage consistency since mixing quotes arbitrarily may reduce reading comprehension/speed.

**Comment by nvuillam** [comment]
Such issue is to adress to lintR maintainers :) -> https://github.com/r-lib/lintr

As said by @Kurt-von-Laven, to disable it you can define a local .lintr config file -> https://lintr.r-lib.org/articles/lintr.html#configuring-linters
