### ISSUE TITLE
ANSIBLE_DIRECTORY not respected

### ISSUE THREAD

**Issue by ishioni** [oxsecurity/megalinter#2132]
**Describe the bug**
Even though ANSIBLE_DIRECTORY is set to a subdirectory of the repo, ansible-lint scans through the whole repository

**To Reproduce**

1. npx mega-linter-runner --flavor terraform -e 'ENABLE=ANSIBLE' -e 'ANSIBLE_DIRECTORY=ansible' -e 'LOG_LEVEL=DEBUG' -e 'ANSIBLE_ANSIBLE_LINT_RULES_PATH=.github/linters/.ansible-lint'
2. I get errors about files in cluster/ or terraform/

**Expected behavior**
ansible-lint would only lint files inside of the ansible directory

**Comment by nvuillam** [comment]
It would require an update in MegaLinter engine , something like a new property cli_lint_mode_project_root that could take $ANSIBLE_DIRECTORY as parameter
can be done someay, or maybe u'd like to make a PR ?

**Comment by ishioni** [comment]
What is that env supposed to do? Because I'm kinda confused by it then

**Comment by Kurt-von-Laven** [comment]
I understand your confusion. From [the MegaLinter ansible-lint docs](https://github.com/oxsecurity/megalinter/blob/c13e920cea92c5276c1d25befe1d5b9561819c84/docs/descriptors/ansible_ansible_lint.md#how-are-identified-applicable-files), I would guess `ANSIBLE_DIRECTORY` is currently only used to determine whether or not to skip running ansible-lint altogether? The section of the docs immediately below that recommends using ansible-lint rather than MegaLinter config options if that is a possibility in this case.
