### ISSUE TITLE
New markdown link checker

### ISSUE THREAD

**Issue by shiranr** [oxsecurity/megalinter#2181]
Hi @nvuillam,

Hope all is well.
In the [CSE Playbook](https://github.com/microsoft/code-with-engineering-playbook), I replaced the markdown link checker with a custom one I wrote in Golang which runs faster.
You can find it [here](https://github.com/shiranr/linkcheck).
Would you be interested in having it as part of Megalinter (Currently we are using it as a [plugin])?(https://github.com/microsoft/code-with-engineering-playbook/blob/change_link_check_and_fix_links/.mega-linter.yml). 

Cheers,

**Comment by nvuillam** [comment]
I can for sure add it in the plugins list, great work :)

About embedding it in the core... can you explain how it runs faster that markdown-links-check ? :)

**Comment by Kurt-von-Laven** [comment]
That's awesome. We have had more false positives from markdown-link-check than from all other linters included in MegaLinter combined, so personally I am excited to see an alternative. Some of this isn't anyone's fault because checking links is inherently flaky, but I do wish it had retry logic, and we've had a few other issues as well. Do you feel that improving the performance of markdown-link-check is prohibitive? I ask because I see value in sharing the maintenance burden with the existing maintainers of markdown-link-check that have kept the tool running for nearly seven years, and it has an existing community of folks invested in it, which proved very helpful when we did encounter issues. I've filed shiranr/linkcheck#1, because I couldn't quickly determine how to configure linkcheck. Thanks for building this neat tool, and I look forward to trying it out.

**Comment by shiranr** [comment]
Thank you @nvuillam I will create a PR for a plugin if that's alright with you.
I am currently working on improving the documentation and do think it is always good to have several options when using any linter.
As can be seen in [this commit](https://github.com/microsoft/code-with-engineering-playbook/pull/907) the MD link checker takes about 4.5 minutes (what made me look for another option), while [with the golang](https://github.com/microsoft/code-with-engineering-playbook/pull/915) it takes around 13 seconds.
Regarding the speed improvements:
1. I use Goroutines to analyze files and find the links in the in parallel. 
2. I use a golang library to perform a fast check over the links (https://github.com/gocolly/colly)

**Comment by Kurt-von-Laven** [comment]
That's very impressive and certainly answers my question about why this needed to be a totally separate linter.

**Comment by nvuillam** [comment]
Great, waiting for the PR :)

**Comment by Kurt-von-Laven** [comment]
@shiranr, [Lychee](https://lychee.cli.rs/) was recently added to MegaLinter in v7.2.0, so I thought of you. We have been very impressed with its reliability so far. It is written in Rust, so I'm guessing it's much faster than markdown-link-check. We [disabled markdown-link-check in our base MegaLinter config](https://github.com/ScribeMD/.github/blob/37e9947f6e4c61752f94f1248358c6307fc93536/.github/base.mega-linter.yaml#L7) to avoid duplication of link checking.
