### ISSUE TITLE
Create a nolint report 

### ISSUE THREAD

**Issue by dschveninger** [oxsecurity/megalinter#2216]
**Is your feature request related to a problem? Please describe.**
The speed of development sometimes nolint commands can increase to the point that the linter configuration needs to be reviewed or the code needs to be re-factored. 

**Describe the solution you'd like**
It would be nice if we could turn on a Deep review switch for Megalinter and the summary report would give nolint commands count by linter type. 

**Describe alternatives you've considered**
We could create a mega linter plug-in that handles it separately, like we did with A TODO counter linter. But I thought this would be a better enhancement If the nolint count was integrated with the linter summary then A separate plug-in report. 

**Additional context**
Just posting this here to get feedback to see if the community likes this idea and if we should consider an open source solution over an internal plug in direction. 

thank you to everybody that supports Megalinter.

**Comment by nvuillam** [comment]
What do you mean by `nolint` ?

annotations/comments in code that says linters to ignore errors ?

**Comment by dschveninger** [comment]
Yes that is correct.
//nolint:gochecknoglobals

**Comment by nvuillam** [comment]
The problem is that all linters have their own annotations and comments

And some of them are for a line, some others for a block of code, some others for the whole file, some are managed in a .ignore file...

Except if the linters themselves were able to count the number of disable stuff they found... I don't see ho we could do that in a generic way within MegaLinter :/

An alternative way that can be used to setup MegaLinter on an existing project is to define a maximum number of errors by linter

![image](https://user-images.githubusercontent.com/17500430/210609313-ce43588a-3546-4046-9360-932470858aa0.png)

You can see more setup strategies in this article: https://nicolas.vuillamy.fr/improve-uniformize-and-secure-your-code-base-with-megalinter-62ebab422c1

**Comment by dschveninger** [comment]
I will consider that.

What do you think about updating the descriptor to support a regex counter for linter overrides? If a linter wants to support it we can just update the descriptor. So if you are doing file or file-based linting could we use that reqex against the files and just report regex count in the summary page? 
https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/go.megalinter-descriptor.yml

**Comment by nvuillam** [comment]
Technically everything is possible, this is more a "philosophical" matter in my opinion :)

## False positives

Lots of linters find issues in specific files that release managers can consider as **false positive** or **not relevant** (that's the case in MegaLinter and most of my projects).

In that case, instead of disabling the rule for all the files, or exclude the file from linting (that would prevent to find errors related to other rules), the use of **inline disable** is recommended (megalinter.io docs contain urls to linter docs explaining how to do that thanks to property `linter_rules_inline_disable_url` in descriptors).

## Dirty code

The use of inline disable should be restricted to "false positives", not to "no time to fix but I need to merge", so using them for both cases would create technical debt because developers won't be able to differentiate false positives from dirty work.

That's why I recommended for "no time to fix but i need to merge" case to use _DISABLE_ERRORS_IF_LESS_THAN. Because that way : 
- inline disable are only for false positives
- dirty code still make linters raise errors and appear in logs
,
## Sneaky devs

There is a 3rd case that would be that you don't trust your developers and are afraid that they inline disable everytime they see an issue.
You can easily spot them with CTRL+F in your sources, but maybe you'd prefer it to make it via CI

### Custom semgrep rule

It seems semgrep allows to define custom rules with generic patterns ( https://semgrep.dev/blog/2020/experimental-feature-generic-pattern-matching )
You maybe write one with `eslint-disable` for example

### New linter

You could find an existing linter doing that more simply than with semgrep and we could add it to MegaLinter (maybe as a plugin for a start)

## Conclusion

All these explanations are opiniotated from my experience (which is far from being universal :) )

**Comment by dschveninger** [comment]
I understand your point of view and thank you for your time on this issues.  I consider it closed.

**Comment by nvuillam** [comment]
@dschveninger you're welcome :)
