### ISSUE TITLE
dotenv linter commits the original file as a separate file

### ISSUE THREAD

**Issue by s-t-hg** [oxsecurity/megalinter#2225]
**Describe the bug**

Thank you for your positive improvements to this wonderful project.

I committed the file `.sample.env` to a private GitHub repository (sorry!) where I have MegaLinter set up, and the backup file was copied by automatic modification.

**To Reproduce**

Commit a invalid .env file.

**Expected behavior**

No backup files are needed.

**Screenshots**

![image](https://user-images.githubusercontent.com/108658936/211129302-1e59facd-386c-41fe-b262-cc17d77715a3.png)

**Comment by nvuillam** [comment]
hi @s-t-hg  :)

1.thanks for your thanks :) ( if your company loves open-source, don't hesitate to [support me](https://github.com/sponsors/nvuillam) haha ^^ )

2. Don't apologize to use private repos, this is normal when you don't want your code to be public :D 

3. this is probably a [dotenv-linter](https://github.com/dotenv-linter/dotenv-linter) issue, but you can easily solve it by adding `*.bak` in a `.gitignore` file at the root of your repository :)

**Comment by s-t-hg** [comment]
> you can easily solve it by adding `*.bak` in a `.gitignore` file at the root of your repository :)

Definitely!

BTW, checking the documentation, it appears that this behavior can be changed; wouldn't it be better to specify this option in MegaLinter?
https://dotenv-linter.github.io/#/usage/fix?id=disable-backup

```sh
dotenv-linter fix --no-backup
```

**Comment by nvuillam** [comment]
You can play wirh arguments using variable `ENV_DOTENV_LINTER_ARGUMENTS` in your .mega-linter.yml config file :)

`ENV_DOTENV_LINTER_ARGUMENTS: ["--no-backup"]`

**Comment by nvuillam** [comment]
(I prefer to not activate it by default, because more and more users are running MegaLinter locally in their computer, and anyway nobody wants to commit .bak files, so .gitignore should be updated to match all the cases from all applications ^^ )

**Comment by s-t-hg** [comment]
Thank you for your immediate reply.

I am in favor of changing the default behavior because I expect that MegaLinter users do not want .bak files, but I respect your decision. Feel free to close this issue.

Finally, let me thank you again. Thank you very much!

**Comment by nvuillam** [comment]
@s-t-hg MegaLinter has a core architecture that handles a single CLI argument `cli_lint_fix_arg_name` from a [descriptor](https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/env.megalinter-descriptor.yml) (`fix` in the case of dotenv linter) when APPLY_FIXES is enabled 

In that case, we need 2 arguments because "--no-backup" has no sense being sent when dotenv-linter is called without autofix

So managing your request would require to either:
- update the architecture so cli_lint_fix_arg_name could take several values ( could be long ^^)
- create a python class just to override this behavior

So their is also a time/maintenance reason for my response :)

But this is not (totally) a dictatorship here... there are also great maintainers and contributors that could think otherwise (and maybe who would make the PR ^^), @Kurt-von-Laven @bdovaz @echoix what is your opinion about the request ? :)

**Comment by Kurt-von-Laven** [comment]
It seems like a reasonable request, so I don't advocate closing the issue won't fix, nor do I advocate @nvuillam taking this work on. @nvuillam already said this, but to elaborate, [`--no-backup` is an argument of `fix`](https://github.com/dotenv-linter/dotenv-linter/blob/2ea708cb5e3c15ca7d116bb20d3889948a91ab28/dotenv-linter/src/cli/mod.rs#L89-L99) and therefore cannot be passed without `fix`. This is a little cheeky, but could one pass a doubly quoted string, such as `"'fix --no-backup'"` as the `cli_lint_fix_arg_name`? That might be something to try, @s-t-hg, if nobody immediately corrects me. If not, personally, I think it's okay if someone else wants to take on one of the two approaches @nvuillam has outlined, and I'm happy to support such an effort, but it may end up being self-serve unless this issue receives more upvotes since the impact of such a change currently seems relatively narrow.

**Comment by nvuillam** [comment]
@Kurt-von-Laven default architecture (Linter.py) calls commands with a list of arguments, not as a string, so `"'fix --no-backup'"` will be consider as an unique argument and won't be recognized :/

But that can be simply done by doing something like :
- defining an additional linter config variable ENV_DOTENV_LINTER_NO_BACKUP
-  overriding Linter.py in a DotenvLinter.py 

```python
command = super.build_lint_command(self,file)
if config.get("ENV_DOTENV_LINTER_NO_BACKUP","false") == "true and self.cli_lint_fix_arg_name in command:
     append --no-backup just after position of cli_lint_fix_arg_name in command
```
