### ISSUE TITLE
Try using npm clean-install production only dependencies

### ISSUE THREAD

**Issue by echoix** [oxsecurity/megalinter#2247]
**Is your feature request related to a problem? Please describe.**

Reading an article about Docker images with node, it had two suggestions that we could consider the difference it makes in the generated images. 

See the article https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/, especially at sections 2 and 3.

**Describe the solution you'd like**
Implement using npm ci --only-production to compare the contents and performance of node-based linters. Make sure the env variable is also set. 

**Describe alternatives you've considered**
The current status with npm install, adding an env variable to indicate production. 

**Additional context**
![image](https://user-images.githubusercontent.com/27212526/211696069-88a5be7a-6028-4611-9720-d156c11a0720.jpeg)
![image](https://user-images.githubusercontent.com/27212526/211696076-bdc74382-87c3-4285-825b-4c5d468a0860.jpeg)
![image](https://user-images.githubusercontent.com/27212526/211696084-fb0dfbe3-79a6-435f-a6f2-8b52c0a634e8.jpeg)

**Comment by nvuillam** [comment]
@echoix that's an excellent proposition :)

NODE_ENV=production is already present in MegaLinter Dockerfiles , but if you find a way to use the --only=production with npm install ( npm ci won't work because we don't have a package-lock.json as wee install packages from their identifier in the command line ), it will again improve performances and probably do much better than the deletion of some files that I call ater npm-install :)

**Comment by echoix** [comment]
I've read that using npm ci --only-production is not the same as adding the env variable, both can be used. 

The package-lock.json was what I was wondering could happen. I knew you worked more on node projects that I did. Does it work with only a package.json? I understand that the command is to keep the exact dependencies that were planned, in order for it to be reproducible (not having it changed at install time), so like using a build stage that creates a package-lock.json and that we only keep that file takes away that purpose.

**Comment by nvuillam** [comment]
@echoix there is no package.json :/

Maybe if you try to add `--production` it will decrease the size !

If not, probably something ugly like the following could work:

```shell
npm install package1 package2 package3... # (what we have today, and generates a package.json, maybe remove the --no-cache) && \
rm -rf /node-devs/node_modules && \ #deletes installed packages & dependencies && \
npm ci --only=production && \ # will use package.json generated by npm install, & reuse the cache for better perfs
 npm audit fix --audit-level=critical || true && \
 npm cache clean --force || true \
```

**Comment by echoix** [comment]
npm ci deletes `node_modules` before starting, that's what the clean install in ci is.

**Comment by echoix** [comment]
But how does one create a package.json/package-lock.json with production-only dependencies if you say npm ci only uses that? It doesn't make sense. If it works like npm install, it really doesn't accept a list on dependencies?

**Comment by nvuillam** [comment]
To build JS packages, you run npm install locally, it generates package.json & package-lock.json, and node_modules is in .gitignore. Then, npm ci is called in CI to install dependencies using package.json & package-lock.json.

But MegaLinter is not a JS package, it just uses JS packages... that's why we directly install them in CI

( it's kind of tricky, i admit ! )
