### ISSUE TITLE
Doubling CI jobs issue for internal contributors

### ISSUE THREAD

**Issue by nvuillam** [oxsecurity/megalinter#2377]
We have 234 CI jobs, it's really too many and when there are several running PR workflows, it generates too much delay

I didn't succeed to configure Build Deploy DEV - Linters job to avoid it to be launched twice... if someone succeeds it it would really improve contributing experience :)

Another solution could be to add a condition to run individual linter checks, so they would be triggered only when we want it, for example if the commit text or PR text contains some word like `check linters`

![image](https://user-images.githubusercontent.com/17500430/219973861-20cfcfca-f6be-46b4-8c67-91f89943649c.png)

![image](https://user-images.githubusercontent.com/17500430/219973838-11eff486-785e-4f3e-9575-7c74e4ccdd96.png)

**Comment by bdovaz** [comment]
@nvuillam the culprit is me in #2294 but we really need a way to run the build+tests of each linter in parallel.

Until now it was only done with a very small subset fixed in the workflows and for me in that PR (#2294) it was super frustrating to have to wait for the task that builds all linters and runs all the tests together (Build MegaLinter Docker Image (full from main repo) and Run Test Cases) and wait half an hour or more for it to fail or not.... By running them in parallel at least it speeds up that process quite a bit....

**Comment by nvuillam** [comment]
I know that, but the is no reason to run twice the same test for a single PR :)
And i still think that it should be "on demand": for example PRs from auto update linters job does not need to run all those checks

**Comment by echoix** [comment]
I stumbled upon this, when I wasn't looking specifically for this https://github.com/fkirc/skip-duplicate-actions. I didn't make my opinion on it yet. But maybe we could try temporarily setting `jobs.<job_id>.strategy.max-parallel` a bit lower especially on jobs that run on main only (or releases), so we could have runners left for other things. (Once in main, it's not as urgent to have all 112 jobs to run as quickly as possible) https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel

**Comment by nvuillam** [comment]
I think I solved it, now the linter jobs are run just once as they are triggered only on pull_request, not push :)
