### ISSUE TITLE
Request new MegaLinter flavor

### ISSUE THREAD

**Issue by jwcastillo** [oxsecurity/megalinter#2405]
MegaLinter would run faster on my project if I had a flavor containing the following list of linters:

ACTION_ACTIONLINT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, GROOVY_NPM_GROOVY_LINT, JAVA_CHECKSTYLE, JAVA_PMD, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER, REPOSITORY_CHECKOV, REPOSITORY_GIT_DIFF, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT, REPOSITORY_TRIVY, SQL_SQL_LINT, SQL_TSQLLINT, XML_XMLLINT, YAML_PRETTIER, YAML_YAMLLINT, YAML_V8R

Would it be possible to create one ? Thanks :relaxed:

**Comment by ThomasSanson** [comment]
@jwcastillo Hello, do you have any name ideas for this flavor ?

**Comment by Kurt-von-Laven** [comment]
This is a proposal to add [tsqllint](https://github.com/tsqllint/tsqllint) to the Java flavor, which already includes all of the other listed linters. The other SQL linters are already included in every flavor, but tsqllint is not, presumably because it's specific to [Transact-SQL](https://learn.microsoft.com/en-us/sql/t-sql/language-reference). That makes this change easy to implement. In my opinion, whether this addition benefits the MegaLinter ecosystem boils down to the size and runtime tsqllint would add to the Java flavor, the popularity of Transact-SQL, and whether it encumbers the out-of-box experience or has some other unique drawbacks such as a high rate of false positives or bugs. It may well be worth including tsqllint in all images like the other SQL linters for all I know, but if someone with more familiarity with tsqllint has thoughts on these matters, that would inform this discussion greatly. For example, a worst case might be that Transact-SQL users make up a small percentage of SQL users and that including tsqqlint in the Java flavor would require the great majority of the flavor's users to disable tsqllint since it would raise many false positives on vanilla SQL. This is purely speculative though; I know not.

**Comment by echoix** [comment]
TSQLint is a dotnet-based linter, which by the current installation method would mean that the whole .NET SDK would be included. (This linter can also be used separately by another installation method, about a 40 MB download).
