### ISSUE TITLE
How to build megalinter image for testing purposes

### ISSUE THREAD

**Issue by dkiziridis** [oxsecurity/megalinter#2484]
Hello, 

I'm trying to build a prod image of megalinter to address [this issue](https://github.com/oxsecurity/megalinter/issues/2384#issuecomment-1462823290). 
I modified the code to make megalinter accept self-singed certs for on-prem Azure DevOps. 

After a few tweaks to the Dockerfile and a lot of headaches with the proxy, I managed to get to step 16/16.

It is, however... failing at this command. 
I am using **RHEL 8.7** and **buildah** in order to build the image. 

`[16/16] STEP 54/86: RUN --mount=type=secret,id=GITHUB_TOKEN mkdir -p ${PWSH_DIRECTORY}     && curl --retry 5 --retry-delay 5 -s        -H "Accept: application/vnd.github+json"        -H "Authorization: Bearer $(cat /run/secrets/GITHUB_TOKEN)"        https://api.github.com/repos/powershell/powershell/releases/${PWSH_VERSION}         | grep browser_download_url         | grep linux-alpine-x64         | cut -d '"' -f 4         | xargs -n 1 wget -O -         | tar -xzC ${PWSH_DIRECTORY}     && ln -sf ${PWSH_DIRECTORY}/pwsh /usr/bin/pwsh
cat: can't open '/run/secrets/GITHUB_TOKEN': No such file or directory
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.`

I understand the issue lies with **GITHUB_TOKEN**, which is missing, but I am unsure as to which token this implies ?
I need to build the image, run some tests locally and then make a PR to add the feature in this repo. 

Any help is appreciated. 

Kind regards, 
Dimitris.

**Comment by nvuillam** [comment]
Github API limits the number of unauthenticated calls, and that mae our CI jobs fail often, that's why we added `$(cat /run/secrets/GITHUB_TOKEN)` in Dockerfile when Github API is called.

`$(cat /run/secrets/GITHUB_TOKEN)` is set by https://github.com/docker/build-push-action , as you can see here for example ->  https://github.com/oxsecurity/megalinter/blob/227ac6b9feb6f8f8a8334ca73cf56452821e827d/.github/workflows/deploy-DEV.yml#L131

So to build locally, you can either:
- remove the `-H "Authorization: Bearer $(cat /run/secrets/GITHUB_TOKEN)"` from your Dockerfile
- Create a [Github Personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and store it locally in a `/run/secrets/GITHUB_TOKEN` file
