### ISSUE TITLE
feat: new link checker - lychee

### ISSUE THREAD

**Issue by DariuszPorowski** [oxsecurity/megalinter#2672]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated with `markdown-link-check`. [lychee](https://lychee.cli.rs/) is an alternative that works IMHO!

**Describe the solution you'd like**

lychee part of megalinter

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Kurt-von-Laven** [comment]
Looks like it can be installed via cargo, and I agree that our community has faced a number of difficulties regarding markdown-link-check, such as security incidents that are fixed a bit slowly and performance issues. The project is currently on life support. My experience has been that the lack of retry logic leads to many more false positives than all other linters combined. We obviously still value having a link checker and were never tempted to disable it, so I don't mean to bash a useful tool. I raise these issues since we are doing a major release, so it would be a good time to take markdown-link-check out if lychee is added within the next week or two. Please let me know if anyone feels that we should keep markdown-link-check in v7.

**Comment by DariuszPorowski** [comment]
@Kurt-von-Laven tried cargo, but it requires to setup deps firs: https://github.com/lycheeverse/lychee#build-dependencies and do not feel it the right approach for megaliter.

**Comment by Kurt-von-Laven** [comment]
Ah, sorry. That makes sense. Whatever is easiest is probably best.
