### ISSUE TITLE
tflint doesn't work in megalinter 7.0.x

### ISSUE THREAD

**Issue by ruzickap** [oxsecurity/megalinter#2699]
**Describe the bug**

It looks like `tflint` doesn't work in megalinter 7.0.x.
Details: https://github.com/ruzickap/k8s-tf-eks-gitops/actions/runs/5114199496/jobs/9194202870

```text
❌ Linted [TERRAFORM] files with [tflint]: Found 5 error(s) - (0.37s) (expand for details)
  - Using [tflint v0.46.1] https://megalinter.io/7.0.3/descriptors/terraform_tflint
  - MegaLinter key: [TERRAFORM_TFLINT]
  - Rules config: [.tflint.hcl]
  - Number of files analyzed: [5]
  [Pre][TERRAFORM_TFLINT] run: [tflint --init --config /action/lib/.automation/.tflint.hcl] in cwd [/github/workspace]
  [Pre][TERRAFORM_TFLINT] error:
  Installing `aws` plugin...
  Failed to install a plugin; Failed to fetch GitHub releases: GET https://api.github.com/repos/terraform-linters/tflint-ruleset-aws/releases/tags/v0.17.0: 401 Bad credentials []
  
  [tflint] terraform/aws-mgmt/data.tf - ERROR - 1 error(s)
  --Error detail:
  WARNING: "tflint FILE/DIR" is deprecated and will error in a future version. Use --chdir or --filter instead.
  Failed to initialize plugins; Plugin `aws` not found. Did you run `tflint --init`?
  
  [tflint] terraform/aws-mgmt/eks.tf - ERROR - 1 error(s)
  --Error detail:
  WARNING: "tflint FILE/DIR" is deprecated and will error in a future version. Use --chdir or --filter instead.
  Failed to initialize plugins; Plugin `aws` not found. Did you run `tflint --init`?
```

Megalinter 6.x.x works fine with `tflint`: https://github.com/ruzickap/k8s-tf-eks-gitops/actions/runs/5112503034/jobs/9190611249

```text
✅ Linted [TERRAFORM] files with [tflint] successfully - (4.78s) (expand for details)
  - Using [tflint v0.45.0] https://megalinter.io/6.22.2/descriptors/terraform_tflint
  - MegaLinter key: [TERRAFORM_TFLINT]
  - Rules config: [.tflint.hcl]
  - Number of files analyzed: [5]
  [Pre][TERRAFORM_TFLINT] run: [tflint --init --config /action/lib/.automation/.tflint.hcl] in cwd [/github/workspace]
  [Pre][TERRAFORM_TFLINT] Installing `aws` plugin...
  Installed `aws` (source: github.com/terraform-linters/tflint-ruleset-aws, version: 0.17.0)
```

Thanks for checking it...

**Comment by nvuillam** [comment]
It's because of secured env variables :/

Probably tflint fetches aws plugin from github.com ,and as we hide GITHUB_TOKEN he doesn't like it...

I'll make a fix to allow variables just for one linter !

**Comment by ruzickap** [comment]
Thanks. It is working fine with the beta :-)

Wouldn't it make sense to add note to the [docs/descriptors/terraform_tflint.md](https://github.com/oxsecurity/megalinter/blob/main/docs/descriptors/terraform_tflint.md) that it is recommended to use `TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN` to make `tflint` working in "GitHub Actions"?

It may not be clear for the end users, that you need this "by default" otherwise `tflint` may not work...

I know that `TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES` is properly documented, but when enduser got the "tflint Bad credentials error" it may not be clear that the GITHUB_TOKEN needs to be added there.

**Comment by nvuillam** [comment]
@ruzickap indeed :)
Wanna make a PR on the terraform descriptor file, or I'll do it later ? :)

**Comment by ruzickap** [comment]
Let me create the PR :-)

**Comment by trevor-vaughan** [comment]
----
> 🦾 Written with LLM assistance [claude-sonnet-5]
> 💪 Reviewed by a human before submission
----

The 2023 diagnosis:

> It's because of secured env variables :/
>
> Probably tflint fetches aws plugin from github.com, and as we hide GITHUB_TOKEN he doesn't like it...

That is the right cause. The detail worth adding is in "as we hide GITHUB_TOKEN": MegaLinter does not hide it, it replaces it with a non-empty invalid string.

`config.build_env` masks rather than deletes ([`megalinter/config.py:378`](https://github.com/oxsecurity/megalinter/blob/7b5f617d0111c4479c934b7630a52a09135df8a9/megalinter/config.py#L378)):

```python
env_dict[key] = "HIDDEN_BY_MEGALINTER"
```

tflint's token lookup treats absent and empty identically, but any non-empty string as a real credential ([`plugin/install.go:467-472`](https://github.com/terraform-linters/tflint/blob/v0.64.0/plugin/install.go#L467-L472) at tag `v0.64.0`, the version currently pinned in the descriptor):

```go
if t := os.Getenv("GITHUB_TOKEN"); t != "" {
	log.Printf("[DEBUG] GITHUB_TOKEN set, plugin requests to the GitHub API will be authenticated")
	return t
}

return ""
```

So `HIDDEN_BY_MEGALINTER` is sent as a bearer credential and rejected. Without it, tflint falls through to an anonymous request. That works, subject to the 60/hour unauthenticated rate limit documented in [tflint's plugin guide](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting).

| Case | `GITHUB_TOKEN` | Result |
| --- | --- | --- |
| A | `HIDDEN_BY_MEGALINTER` (what MegaLinter sends today) | `401 Bad credentials`, exit 1 |
| B | absent | Installed, exit 0 |
| C | empty string | Installed, exit 0 |

<details>
<summary>Full reproduction (tflint v0.64.0, official release binary)</summary>

With this `.tflint.hcl`:

```hcl
plugin "aws" {
  enabled = true
  version = "0.44.0"
  source  = "github.com/terraform-linters/tflint-ruleset-aws"
}
```

Case A:

```console
$ env -i PATH=/usr/bin:/bin HOME=$PWD GITHUB_TOKEN=HIDDEN_BY_MEGALINTER \
    ./tflint --init --config $PWD/.tflint.hcl
Installing "aws" plugin...
Failed to install a plugin; Failed to fetch GitHub releases: GET https://api.github.com/repos/terraform-linters/tflint-ruleset-aws/releases/tags/v0.44.0: 401 Bad credentials []
```

Case C:

```console
$ env -i PATH=/usr/bin:/bin HOME=$PWD GITHUB_TOKEN= \
    ./tflint --init --config $PWD/.tflint.hcl
Installing "aws" plugin...
Installed "aws" (source: github.com/terraform-linters/tflint-ruleset-aws, version: 0.44.0)
```

I also confirmed the MegaLinter side by importing the real `megalinter/config.py` from `main` ([`7b5f617d01`](https://github.com/oxsecurity/megalinter/commit/7b5f617d0111c4479c934b7630a52a09135df8a9)) and replaying the sequence in [`pre_post_factory.py:126-137`](https://github.com/oxsecurity/megalinter/blob/7b5f617d0111c4479c934b7630a52a09135df8a9/megalinter/pre_post_factory.py#L126-L137). With `GITHUB_TOKEN` set and no `TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES`:

```text
GITHUB_TOKEN key present: True | value: 'HIDDEN_BY_MEGALINTER'
```

The key is present with the sentinel, not absent.

</details>

## Why it still matters

`<LINTER>_UNSECURED_ENV_VARIABLES` (#2703) fixed the reported symptom, and the [follow-up request in this thread](https://github.com/oxsecurity/megalinter/issues/2699#issuecomment-1569578885) produced the note now at [`terraform.megalinter-descriptor.yml:41`](https://github.com/oxsecurity/megalinter/blob/7b5f617d0111c4479c934b7630a52a09135df8a9/megalinter/descriptors/terraform.megalinter-descriptor.yml#L41):

> If you are using the GitHub action please use the `TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN` to prevent plugin download issues

That resolves the failure by giving the linter a real credential. Since the tool does not need one, a couple of things are still true on `main`:

- Out of the box, tflint on github.com fails for anyone who has not found that note. An anonymous install would have worked.
- The advice asks users to expose a real token to a linter, which sits awkwardly next to the goal of the secured-variables feature.
- The GHE case in #2947 built on the same premise and was solved by adding a second credential variable (`PAT_GITHUB_COM`) that bypasses redaction. Details in https://github.com/oxsecurity/megalinter/issues/8795.

## Suggested fix

Give `tflint --init` an empty or absent `GITHUB_TOKEN` when no usable github.com credential is available, so it degrades to anonymous instead of failing. Case C shows an empty value is enough, so no env-deletion plumbing is needed.

Two shapes, both confined to existing code:

- Extend `replacement_env_vars` so a missing `var_src` clears `var_dest` rather than leaving the mask. Smallest change, but it also affects user `PRE_COMMANDS`.
- Add a dedicated `command_info` property (e.g. `clear_env_vars`) used from `TfLintLinter`. A little more surface, no change to existing behavior.

This is not a proposal to remove `<LINTER>_UNSECURED_ENV_VARIABLES`. It stays useful for raising the API rate limit and for private plugin repos. The goal is that leaving it unconfigured degrades to a working anonymous install rather than a hard failure.

Worth checking whether tflint is the only linter affected: masking with a non-empty sentinel is harmless for tools that merely *read* a value, but breaks any tool that *authenticates* with it.

<details>
<summary>Verification notes</summary>

Verified on MegaLinter `main` @ [`7b5f617d01`](https://github.com/oxsecurity/megalinter/commit/7b5f617d0111c4479c934b7630a52a09135df8a9), tflint `v0.64.0` (pinned at [`terraform.megalinter-descriptor.yml:78`](https://github.com/oxsecurity/megalinter/blob/7b5f617d0111c4479c934b7630a52a09135df8a9/megalinter/descriptors/terraform.megalinter-descriptor.yml#L78)), using the official linux/amd64 release binary. I could not run a full MegaLinter Docker image (no container runtime available), so the tflint half used the pinned binary directly rather than the built `terraform_tflint` image.

</details>
