### ISSUE TITLE
Various Makefile errors on macOS

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#2863]
**Describe the bug**
A number of issues have spawned from my clean checkout of the Megalinter repository:

1. The `make help` command references `make bootstrap-dev`, but this target does not exist

```
$ make help
How to use me:
 make help
 make bootstrap-dev
...

$ make bootstrap-dev
make: *** No rule to make target `bootstrap-dev'.  Stop.
```

2. Running `make bootstrap` results in an EOF error:

```
$ make bootstrap
/bin/bash: -c: line 1: syntax error: unexpected end of file
make[2]: *** [python-venv-init] Error 2
make[1]: *** [python-bootstrap] Error 2
make: *** [bootstrap] Error 2
```

Version: 7
Platform: macOS (Silicon)

**Comment by ThomasSanson** [comment]
@nvuillam,

I wish to apprise you that I have been on paternity leave since the 28th of July. Upon my return, I shall endeavour to address this matter post-haste

I deem it imperative, in the initial instance, to revisit the documentation

@andrewvaughan, the Makefile, to the best of my recollection, has been chiefly designed for a standard utilisation on Gitpod, and hence, specifically on Linux (Ubuntu, to be precise). The discrepancy you have encountered appears to be due to your use of a shell other than bash; might you be employing zsh ?

Could I kindly request that, as a preliminary step, you execute bash from your terminal using the following commands:
```bash
$ /bin/bash
$ make bootstrap
```

You are at liberty to peruse the contents of the Makefile. However, I would earnestly advocate for the use of Gitpod for your contributions, until such time as I can enlist the assistance of a colleague with a Mac to effectuate the requisite corrections

Furthermore, @nvuillam, should it transpire that we are to accommodate a plethora of platforms (Windows, Linux, MacOS), I am of the opinion that it would be prudent for me to allocate a significant portion of time to transition from Makefile to Taskfile. The latter, indeed, provides a more generic approach and would empower us to manage platforms autonomously

**Comment by ThomasSanson** [comment]
Lastly, @nvuillam, might I kindly request that you assign this particular issue to me? I believe I am well-positioned to address the concerns raised herein

**Comment by nvuillam** [comment]
@ThomasSanson don't worry if you have a baby to take care, take the time you need , there is no deadline as we can still contribute without gitpod:)
