### ISSUE TITLE
Publint integration

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [oxsecurity/megalinter#2893]
**Is your feature request related to a problem? Please describe.**
Correctly publishing packages in the JS (CJS and ESM) ecosystem is hard these days

**Describe the solution you'd like**
Publint/pkg integration in Megalinter

**Additional context**
Publint web: https://publint.dev/
Publint installable package GH refernce: https://github.com/bluwy/publint/tree/master/pkg

**Comment by echoix** [comment]
I really like the idea! It seems complementary to the JavaScript linters here, from what I see.
The rules described in https://publint.dev/rules are limited, but simple to understand.
The only thing is that the project seems still young, but had releases for more than a year, and didn't reach a v1 yet. But with a 668 stars, it's got a little traction ;)

Did you have a little experience using it with a project?

I'm curious to see the output of 
`npx publint --help`, to look at the possible options for integrating it, since the online documentation doesn't seem to have that information without calling it locally.

**Comment by AndreaPontrandolfo** [comment]
> Did you have a little experience using it with a project?

Sure, we use it at work in our monorepo. And also i use it on some personal projects.

> I'm curious to see the output of
> npx publint --help, to look at the possible options for integrating it, since the online documentation doesn't seem to have that information without calling it locally.

Output:

>   Usage
>     $ publint <command> [options]
> 
>   Available Commands
>     run     Lint a directory (defaults to current directory)
>     deps    Lint dependencies declared in package.json
> 
>   For more info, run any command with the `--help` flag
>     $ publint run --help
>     $ publint deps --help
> 
>   Options
>     --level          Level of messages to log ('suggestion' | 'warning' | 'error')  (default suggestion)
>     -v, --version    Displays current version
>     -h, --help       Displays this message

When i use it, i use it without argument, i just command `publint` and that's it

**Comment by nvuillam** [comment]
I agree, such linter seems interesting :)

@AndreaPontrandolfo would you like to make a PR ? ( with our support ^^ )
