### ISSUE TITLE
megalinter-incremental vs. megalinter-full

### ISSUE THREAD

**Issue by ggalfrin** [oxsecurity/megalinter#2923]
Hey,

I’m using the .pre-commit-config.yaml, and wanted to know what is the difference between “megalinter-incremental” and “megalinter-full”, in terms of which linters run at which phase? (it looks like some linters such as “checkov” and “kics” runs only under “megalinter-full”).

Thanks!

**Comment by Kurt-von-Laven** [comment]
`megalinter-incremental` skips linters that run in project mode, meaning linters that can only run on all of the files rather than a list of modified files. Such linters fundamentally lack support for running incrementally and tend to be slower when relatively few files were modified. `megalinter-full` runs all project mode linters on all files and all other linters on the modified files. You can look in `megalinter-reports/linter-logs/` to see exactly which linters are run in your repository in each case. We run `megalinter-incremental` pre-commit and `megalinter-full` pre-push. We run `megalinter-full` in CI and explicitly pass pre-commit `--all-files` in CI so that issues don't get missed.
