### ISSUE TITLE
Gitleaks --no-git don't work anymore

### ISSUE THREAD

**Issue by snaquekiller** [oxsecurity/megalinter#2945]
**Describe the bug**
Hello, when i try to pass  --not-git for gitleaks argument, it's never work as long as it's git repos. 

**To Reproduce**

1. Add "--no-git" to REPOSITORY_GITLEAKS_ARGUMENTS
2. run megalinter in git repository
3. it's will scan the whole repo with all git commit

**Expected behavior**
Should not read commit.

**Additional context**
I suppose that the problem commit is : https://github.com/oxsecurity/megalinter/commit/7ff24de353661f6cd3d49ea1c9ee77b5b9c562dd#diff-a99fcd6a981aa3d1d5a58aced014f97230d5e2f948e99cdc3f068330e3cca579

**Comment by nvuillam** [comment]
@DariuszPorowski please could you have a look ? :)

**Comment by VictorRos** [comment]
Hello!
I'm working with Nicolas.
He's currently in vacations, but I can follow up this issue if you have questions.
Since condition has changed, option `--no-git` is always removed.

**Comment by riccardos77** [comment]
Hello, same problem here.
Please can you tell me if there is a parameter configuration that allows you to analyze only the current files and not the Git history like --no-git argument?

thanks

**Comment by nvuillam** [comment]
@VictorRos @DariuszPorowski any chance you can have a look at this regression to allow --no-git to be used again? :)

**Comment by DariuszPorowski** [comment]
@nvuillam I am on vacation now. Going back in 3 weeks.

**Comment by riccardos77** [comment]
hello, any update for this issue? thanks

**Comment by Kurt-von-Laven** [comment]
This is not a well thought out idea, but I wonder if there is a way to workaround this by passing something clever to Gitleaks using `--log-opts`.

**Comment by finnlander** [comment]
> **Additional context** I suppose that the problem commit is : [7ff24de#diff-a99fcd6a981aa3d1d5a58aced014f97230d5e2f948e99cdc3f068330e3cca579](https://github.com/oxsecurity/megalinter/commit/7ff24de353661f6cd3d49ea1c9ee77b5b9c562dd#diff-a99fcd6a981aa3d1d5a58aced014f97230d5e2f948e99cdc3f068330e3cca579)

I think the changed line 72 is the culprit here:

- previously there was "else if"-condition (i.e. if `--no-git` was not in the custom parameters, but is in the `cmd`, added by ML)
- now there is simply "if"-condition, separated from the custom parameters check (if `--no-git` is included by any reason -> ignore it) 

I've been "struggling" with the same issue here as in my case:

- Gitleaks execution for the entire repository takes about 600 seconds (i.e. way too long for reasonable fast feedback loops)
- It seems that `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN` is not working when using `push` event trigger in GitHub (the code assumes use of `pull-request` trigger and of course the parameter name suggest it too) -> I want to trigger the MegaLinter a bit quicker/earlier, hence using `push` events.
- And using `--no-git` does not work currently as the value is omitted.

Any ideas on how to work around the issue or a bugfix release would be much appreciated :smile: .

**Comment by nvuillam** [comment]
@DariuszPorowski will you find the time to solve the issue, or is it faster if someone else investigates it ? :)

**Comment by DariuszPorowski** [comment]
@nvuillam unfortunately in the upcoming period I cannot handle this due to personal/work stuff. Probably closer to the EOY I can jump back to some open-source contribution.

**Comment by VictorRos** [comment]
Hi!
I took time to contribute on MegaLinter to try fixing the problem.
PR is opened.
Wait and see!

**Comment by nvuillam** [comment]
Fixed :)

@VictorRos If you can confirm with beta version, it's nice ^^

**Comment by snaquekiller** [comment]
that seem work on one of my repository i test . If other people can confirm that ok :)

**Comment by nvuillam** [comment]
@snaquekiller thanks for your feedback :)

**Comment by VictorRos** [comment]
@nvuillam I confirmed, @snaquekiller tested it for me 😄

We had a use case this morning where a developer had a problem with **MegaLinter** `7.2.1` and we didn't get the problem with **MegaLinter** `beta`.

We are waiting for next release to upgrade to next version all our repositories.

**Comment by nvuillam** [comment]
@VictorRos thanks for the feedback :)

The next release should happen this week-end :)
