### ISSUE TITLE
GHA fails new actionlint

### ISSUE THREAD

**Issue by max-sixty** [oxsecurity/megalinter#2963]
**Describe the bug**

The suggested GHA workflow fails with the latest actionlint linter: https://results.pre-commit.ci/run/github/449091292/1695063235.7tYTqfzvS4asLD5xzP8zWg

I think I mentioned before — to the extent that megalinter could package up the action, rather than supply an 189-line file for folks to copy into their project, that would be a nice way of encapsulating it. With the existing setup, I'm guessing everyone will have to update the action themselves — not a great stress, but less elegant than a single central update.

Thank you!

**Comment by Kurt-von-Laven** [comment]
There is already [an official MegaLinter action](https://github.com/marketplace/actions/megalinter), but I don't see any issue with offering a callable workflow as well. Since you use pre-commit.ci, you may be interested in [ScribeMD/pre-commit-action](https://github.com/ScribeMD/pre-commit-action), which we use to run MegaLinter on GitHub Actions via pre-commit. It leverages asdf to keep your dev environment and CI pinned to the same versions of dev tools and some GitHub Actions features to setup and run pre-commit efficiently and reproducibly. On GitHub Actions, I suspect MegaLinter performs best when pulling the image from the GHCR (GitHub Container Registry) rather than the default of Docker Hub. mega-linter-runner takes [an `--image` flag](https://megalinter.io/latest/mega-linter-runner/#usage) that can be used to change registries (e.g., `npx mega-linter-runner --image ghcr.io/oxsecurity/megalinter-javascript:v7.3.0`).

**Comment by max-sixty** [comment]
> There is already [an official MegaLinter action](https://github.com/marketplace/actions/megalinter), but I don't see any issue with offering a callable workflow as well.

Yes great, this is what I was thinking.

---

(though tbc, we can close this when the workflow passes the lint, the maintainers have much more context than I do on how they want folks to consume megalinter...)

**Comment by max-sixty** [comment]
I'm not sure if it's still an issue, though I'll leave it up to the maintainers to manage...

**Comment by max-sixty** [comment]
I'm not sure if it's still an issue, though I'll leave it up to the maintainers to manage...
