### ISSUE TITLE
Lack of consistency between Github Status and Github Comment Publisher config

### ISSUE THREAD

**Issue by priorax** [oxsecurity/megalinter#2980]
I'm unsure if this is a bug or a feature or quite what.

When looking at both these reporters, I have found that there are a number of undocumented env vars required for GHE usage (eg, use of GITHUB_REPOSITORY and the GITHUB_REF)

The other thing I noticed was that the Comment Reporter allowed for [other methods](https://github.com/oxsecurity/megalinter/blob/main/megalinter/reporters/GithubCommentReporter.py#L89) of authentication in the code other than `GITHUB_TOKEN` but that this is both an unavaliable code path (due to needing a `GITHUB_TOKEN` to get here in the first place).

**Comment by priorax** [comment]
I did try and put something together to help with this but couldn't get a stable devcontainer/gitpod going and I am having issues running the Makefile on OSX, so may try later on WSL on another machine

**Comment by nvuillam** [comment]
GITHUB_REPOSITORY and GITHUB_REF are default environment variables set by Github Actions itself, so no need to document them as they don't need to be specified in the pipelines :)

There are some use cases where you don't want to use default GITHUB_TOKEN, but a Personal Access Token that will have more rights (ex: run again GitHub Action Workflows after MegaLinter pushes a new commit with autofixes)

This is documented in Apply fixes doc -> https://megalinter.io/latest/config-apply-fixes/#apply-fixes-issues

It does not need to be documented in GitHub Comments Reporter, because workflow permissions allow to update comments with GITHUB_TOKEN

**Comment by priorax** [comment]
But is that making an assumption that this is always run in a github actions workflow?

I was trying to use it in an alternative CI tool which communicated back to GHE and that caused issues when pulling tflint (which I saw mentioned in another env var).
Would it perhaps make sense to also include a variable like GHE_TOKEN which can be used in these scenarios but not for pulling linters?

If I'm reading what you're saying properly, what I should do as a workaround to cover both is to get a github token to pull tflint, use PAT to do comment reporter.

But the PAT still would not let me do Github Status Publisher since it's coded to only use access token
https://github.com/oxsecurity/megalinter/blob/main/megalinter/reporters/GithubStatusReporter.py#L59

**Comment by nvuillam** [comment]
@priorax would it be ok if it used GITHUB_TOKEN only if PAT is not defined , like in other places of MegaLinter ?
