### ISSUE TITLE
Create Docker tags that update dependencies regularly, but not MegaLinter beta changes

### ISSUE THREAD

**Issue by andrewvaughan** [oxsecurity/megalinter#3015]
**Is your feature request related to a problem? Please describe.**
The current `v7` tag on Docker hub is nearly a month old - some dependencies like https://github.com/errata-ai/vale have had 5 minor releases in that time (and they have had a number of elements fixed that are now bugs within the current `v7` Docker image).

Would it be possible to have a daily build available that simply ensures that all dependencies are using their `latest` tag, but not a `beta` release that might introduce instability from MegaLinter repository changes? That's what I, personally, expected the `latest` tag to be.

**Describe the solution you'd like**
Ensure that dependencies are up to date with daily builds of the `latest` Docker tag.

**Describe alternatives you've considered**
Create a separate tag explicitly for applying the latest dependencies on top of the most-recent stable change.

**Additional context**
N/A

**Comment by Kurt-von-Laven** [comment]
We don't have a fully automated release process, so this seems challenging. I am not sure how much value a daily release without accompanying documentation of the versions each linter is at would have.

I could hypothetically imagine a daily `canary` build, but any daily-updated build would have to be tested only by automation and be relatively unstable. @nvuillam can speak more precisely on how many bad linter upgrades there are, but rolling those back is one of the significant labors of love he performs on behalf of the MegaLinter community. Without significantly more automated testing, I wouldn't necessarily expect a `canary` build to see much adoption.

That being said, I imagine we would be stoked to receive contributions that improve the extent of automation in either our release process or testing, which would bring us a step closer to your proposal and be very beneficial in their own right.

In the meantime, if daily updates are sufficiently important to you, you might either maintain and publish a `canary` Docker image yourself, or run the individual linters that offer a [pre-commit](https://pre-commit.com) hook via a `.pre-commit-config.yaml` rather than MegaLinter. In either case, you could use a tool like [Renovate](https://docs.renovatebot.com) to keep the linters up-to-date.

**Comment by nvuillam** [comment]
@andrewvaughan there is no official release calendar, but usually we release a minor version every month :)

About the next one, I unfortunately broke mega-inter-runner while converting it as an ES module, so I have to fix it before releasing it again ^^

We have auto update linters job, that we manually merge, and that automatically generates a beta version, there can be new ones everyday except when the CI jobs are failing and manual updates requires to be done.

Earliest beta version is 8 hours old and its content / linter versions is available in beta doc -> https://megalinter.io/beta/all_linters/

Vale is at version 2.29.5 there :)

**Comment by andrewvaughan** [comment]
All fair points! I do think it will become more of a prevalent issue as MegaLinter supports more and more technologies. Many incorporated techs are being added while at very-early stages of their development, meaning they'll see many important releases well past the monthly release cycle.

Another option may be to have a separate "full" flavor that only has well-established linters... but that's getting very complex and I fear is an anti-pattern not really solving the issue. (Thinking outloud).

At the moment, `beta` isn't an option, only because - while it has the lastest stable releases of all dependencies and linters - it includes non-stable additions from the MegaLinter project, itself.  This is a unique situation where the ML project is heavily based around providing the services of dependencies, and not the other way around.

In that stead - the other option may be to change how `beta` builds are performed - that is, creating two releases during `beta` - one that includes the true MegaLinter beta, and one that includes the daily build for the dependencies.

It does seem to me that fully-automating the release process would be a dependency to make this work. Is the lacking automation documented somewhere? I tend to gravitate toward adding efficiency/automation to projects, so I may be able to help.

**Comment by nvuillam** [comment]
@andrewvaughan I see what you mean, but it would require 2 parallel streams in git branches, one for dependencies and one for enhancements... and sometimes both are mixed in the same PR (sometimes a version of a new linter forces us to update ML core architecture to be able to take in account new specificities)

If we had full time resources working on MegaLinter, I would say yes, but the few of us active maintainers struggle enough to handle the single next version stream, and I fear having both would be a nightmare to handle when we need to merge them for a new version ^^

In case people want latest version of some linters, workaround are already existing, like using [PRE_COMMANDS](https://megalinter.io/latest/config-precommands/) to install the latest version of a linter :)

What could eventually work better is that if the team grows (for example if Super-Linter joins here ^^), we could release minor versions more frenquently, like every week, and keep too impacting updates in lower sub branches , something like: 

- main
   - dependencybranch1
   - dependencybranch2
   - dev
     - feature1
     - feature2 
     - ...

**Comment by Kurt-von-Laven** [comment]
In terms of automating the release process, the best solution I have seen other projects using is [Semantic Release](https://github.com/semantic-release/semantic-release), which distributes the work of the release among the commit authors and reviewers, simply requiring use of correct commit prefixes.

**Comment by andrewvaughan** [comment]
@Kurt-von-Laven That's interesting - I wasn't aware of that project, so thank you. It fits in perfectly with my normal [Contributing Guidelines](https://github.com/andrewvaughan/template-core/blob/main/.github/CONTRIBUTING.md) that follow that practice almost to a point.

From what I've seen - it looks as thought GitHub can do 99% of what's listed natively now, but I need to review further.

**Comment by Kurt-von-Laven** [comment]
Do you have a link to GitHub's native release automation support? Having trouble finding documentation about that.

**Comment by andrewvaughan** [comment]
Apologies, I don't have anything offhand... I'm actually working on setting up a base template to redo this right now in my projects, so if I have anything that can cross-reference or help I'll be sure to add. Quickly going through the list of features in the project, though, it seems it can mostly be done with GHA or other services:

| Feature | GitHub |
| :------ | :----- |
| Fully automated release | Certainly feasible through GitHub actions (see: Megalinter!) |
| Enforce [Semantic Versioning](https://semver.org/) specification | I do this by the new [Rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) feature for release branches |
| New features and fixes are immediately available to users | Can be done through Actions (I'm planning on running my CI/CD and SDLC through https://github.com/actions/github-script but I imagine there are other deployment pipeline controllers available |
| Notify maintainers and users of new releases | My releases are done through PR to environment branches, which anyone watching the repository can subscribe to |
| Use formalized commit message convention to document changes in the codebase | I am doing this through GitHub Actions and a linting script |
| Publish on different distribution channels (such as [npm dist-tags](https://docs.npmjs.com/cli/dist-tag)) based on git merges | GitHub Actions |
| Integrate with your [continuous integration workflow](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/README.md#ci-configurations) | Depends on the CI tool (I use GitHub for all of my CI) but most have either Workflow or Webhook integrations |
| Avoid potential errors associated with manual releases | Well, this is just CI/CD |
| Support any [package managers and languages](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/README.md#package-managers-and-languages) via [plugins](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md) | N/A |
| Simple and reusable configuration via [shareable configurations](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/shareable-configurations.md) | GitHub Templates (what I'm working on, now) |
| Support for [npm package provenance](https://github.com/semantic-release/npm#npm-provenance) that promotes increased supply-chain security via signed attestations on GitHub Actions | GH Actions |

Again, I'm _very_ newly introduced to that project, so I could be way high on the Dunning-Krueger graph here, but that seems to be covered mostly for me. I've been doing CI/CD SemVer releases for some time via GitHub, and am now standardizing my core template around automating them. I even am implementing more improved steps like automating Status labels on Issues and PRs when actions are taken, such as:

1. Issues that are approved/triaged automatically get a `Pending Initiation` label
2. When a branch is created in the prescribed format (`ops/00034/some-issue` would be Issue #34 for an Operational initiative, as an example) it automatically updates the Issue to `In Progress`
3. When a PR is made for a branch (with the top commit message in a format like `Ops: Fixing some issue (closes #34)`), that same Issue targeted gets moved to `Code Review`
4. When the PR is accepted and the change is squashed/merged (part of my SDLC standard) the issue automatically goes to the `Pending Staging` status
5. When a staging Pull Request is created from branches `main` to `staging` with the above Commit message included, and it is accepted, the Issue automatically goes to `Staged` and the deployment for the `beta` build is released
6. When a production PR is created from `staging` to `production` with any issues listed in commit messages and the deployment for the next semver build is released

As for number 6 above - I still have some research to build in some type of in-place formatting to determine release, minor, or major releases as part of the standard - currently I do things like move GitHub `latest` tags to help with things like badges and other automations.

I've done some considerable testing and am 95% sure I can make the entire automation above happen with the `actions/scripts` GitHub extension. I also wrote a small Workflow library that allows this to be done in a unit-testable set of javascript/typescript files instead of writing a bunch of code in YAML, which was a savior. I'll share if interested, as it's next on my list to finish.

**Comment by Kurt-von-Laven** [comment]
Thank you for sharing your work with our community and for teaching me about rulesets, which I will see about setting up.

I don't agree that MegaLinter is an example of a fully automated release process. It's of course possible to implement bespoke CD in GitHub Actions, but there are many existing tools that do this already, so it isn't something I would be inclined to recreate personally. I say this having a much worse understanding of your requirements than you do, and I could certainly believe that a number of the features you want might be difficult to find off the shelf.

If you are looking to support many package managers and programming languages, I recommend taking a look at [asdf](https://github.com/asdf-vm/asdf). We use it to keep our tool versions on sync between developers and GitHub Actions. You are also welcome to take any ideas you please from [our template-repo](https://github.com/ScribeMD/template-repo), which supports all major package managers, languages, and platforms (largely thanks to MegaLinter, [pre-commit](https://pre-commit.com), asdf, and GitHub Actions. We use Commitizen only because I wasn't aware of semantic-release at the time, but both are good tools. We do a lot of caching to run MegaLinter and our other pre-commit hooks as quickly as possible in GitHub Actions.

When you say `actions/scripts`, are you referring to [`actions/github-script`](https://github.com/actions/github-script)?

Regarding your Workflow library, are you aware that [GitHub Actions has native support for JavaScript actions](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action)?

In case this helps you or anyone else who reads this thread, I have had a lot of success discovering tools via [GitHub topics](https://github.com/topics/) and [ChatGPT](https://chat.openai.com).
