### ISSUE TITLE
Accessibility linters (e.g., Pa11y, axe, etc.)

### ISSUE THREAD

**Issue by wesley-dean-flexion** [oxsecurity/megalinter#3088]
**Is your feature request related to a problem? Please describe.**

Many of my projects include user accessibility testing requirements and these are often documented in contractual QASPs (Quality Assurance Surveillance Plans).  As a result, we typically include CI/CD workflows to run MegaLinter (because who wouldn't!?!?) as well as pa11y.  It could be kinda nice if pa11y could be integrated as yet another linter.

**Describe the solution you'd like**

I would like another linter added that would run [pa11y](https://github.com/pa11y/pa11y) or [axe](https://www.deque.com/axe/) .

**Describe alternatives you've considered**

When we need to include pa11y, it's typically brought in by using a separate GitHub Action:

* [BEARS](https://github.com/GSA/usagov-benefits-eligibility/blob/main/.github/workflows/pa11y.yml)

**Additional context**

I'm focusing on pa11y because that's where I have the most experience.  Other folks swear by axe and that's cool..  I just know less about how it's implemented.

Pa11y is an open source project written in Node, so it's not far from some (many) of the other linters included with MegaLinter.  The typical flow is for a process (e.g,. `npm run dev` or nginx) to run to listen to a port on the local system (default is 3000, I think) and for another process to run `npm run test:pa11y` (or whatever script the developer codified their package.json).

Here's what I see are the primary complications:

1. pa11y would need a sidecar process to serve the content to check (so, Docker in Docker?  forking?  Python's `subprocess.run()`?)
2. how the process is served could vary wildly from project to project (consider a Node project vs one in Python / Django)

It's not lost on me that many of the projects with which I'm involved have requirements that aren't universal to all projects -- that this can be a somewhat niche consideration.  That said, I suspect that a very common desire for projects with web user interfaces is that users should be able to use those user interfaces.  Having the ability to add a configuration line to one's `.mega-linter.yml` file and receive some feedback about potential accessibility issues could be useful or even educational.

Just an idea.  If it's too much work -- if the juice isn't worth the squeeze -- that's cool.  It's a bit of a departure from the majority of the other linters, not to mention the fact that the implementation / execution could be a challenge to make work smoothly, not to mention that it's sufficiently straight-forward to implement Pa11y in a separate workflow.

**Comment by nvuillam** [comment]
Technically anything is possible, but I'm not sure is it the role of MegaLinter to test external websites ^^

Can pa11y run on local sources ?

**Comment by nvuillam** [comment]
So it would mean to run a local server to execute tests.... I think we are out of MegaLinter linter scopes that are based on source code ^^

But if you want to embed such tests within a MegaLinter run, you could build a plugin :)

**Comment by Kurt-von-Laven** [comment]
Yeah, I also view MegaLinter as a static analysis tool and can't think of any exceptions to this in the existing set of linters. Its core logic is predominantly focused on concurrently running tools on files with certain extensions, which seems unhelpful for pa11y. Is it possible that the server could be launched via a MegaLinter pre-command so that the linter doesn't require special support? If you do build a plugin, it sounds like it would have to run in project (rather than list of files) mode since I don't see how we could hope to detect which files affect the server in a general way (short of using AI ha ha). Nothing wrong with that. In case your goal is really to have a single command that runs all your checks, we instead run both our tests and MegaLinter via [pre-commit](https://pre-commit.com).

**Comment by echoix** [comment]
I tried to take a look at both of the tools you mentioned. Indeed, both have a strong use of a web server. But it seems it may be best suited to run these tools as a npm test for the project. @axe-core/cli explains it better.

But overall, if there are other tools that run more on the contents (rather than on runtime running the project), it would be a really good idea to have some in MegaLinter.

**Comment by wesley-dean-flexion** [comment]
Thank you for your excellent points, all -- they're greatly appreciated!

If I may, I would like to distill down the main points so that I'm sure I understand them and folks coming behind have something with which to refer.

1. MegaLinter is primarily a static code analysis tool.  Pa11y, axe, etc., while good tools, are intended to perform dynamic analysis of running applications.

2. MegaLinter generally scans a list of files or the entire repository; therefore, scanning even a single page may be the result of multiple files.  Consequently, it's misaligned with MegaLinter which, at its core, attempts to report findings on files.

3. It may be possible to accomplish integrating Pa11y (or axe); however, doing so would likely involve significant effort, both in developing the infrastructure to enable such a feature and at runtime to build the things to be scanned.  If one were to proceed, a plugin or `*PRE_COMMANDS` may be able needed to make this happen.

4. There may be the possibility that MegaLinter could be used to scan external sites, either due to accidental or intentional misconfiguration.  That's bad.

Did I capture those thoughts correctly?

Thank you for the opportunity to discuss this with you and, especially, for all of your hard work on behalf of MegaLinter and its community.  :heart:

**Comment by Kurt-von-Laven** [comment]
I am attempting to explain further not out of annoyance, but rather in case it's helpful since I didn't go into as much detail initially. I can imagine my initial reaction coming across as fairly arbitrary.

1. Yes, and to elaborate on why this matters, it's essentially a question of (a) keeping the scope of the tool manageable to maintain and its purpose clear for users and (b) maximizing code reuse since there is higher overlap in core functionality that supports static analysis tools.
2. Yeah, that is correct. We do support a project mode for linters that simply run on the entire project, so it's possible to run Pa11y (and many other things) through MegaLinter. I realize that the definition of "linter" is fairly ambiguous, and some may consider Pa11y a linter even though I personally do not.
3. I am willing to believe that running Pa11y through MegaLinter may turn out to be simply a matter of firing up the server in a pre-command. I'm more skeptical that this would be easier or more productive than running Pa11y through some other tool like pre-commit or a `package.json` script, but that's not really my business. If we were to officially distribute Pa11y, if nothing else we would need some standardized way of launching everyone's server. Would we try to detect the package manager and run `npm start`, `yarn start`, etc. as appropriate? What happens if they have a Flask server? Would we require that users set a config variable with the command to launch their server? This last approach might make a lot of sense if MegaLinter were a tool for validating web applications at runtime, but it holds less appeal as a feature with low prospects of reuse that is orthogonal to the rest of our code base.
4. I think you already laid this concern to rest for us if I understood correctly. It's hard to offer guarantees of good behavior from many-purpose tools if they are misconfigured by a developer. As MegaLinter supports arbitrary pre/post-commands, it will happily do any good or bad thing it is instructed to.

Thanks for reaching out. This has definitely been a thought-provoking discussion for me. I hadn't put much consideration into where precisely we should draw the line regarding which tools we include, because it hadn't really come up. Sorry this wasn't the answer you were hoping for.

**Comment by nvuillam** [comment]
I learn lots of things while working with OX Security experts, and I think I can have a simple answer :)

MegaLinter focuses on static scan tools (SAST, IaC, SBOM :) )

![Security-Scanning-Tools-Defined-1024x576.png](https://github.com/oxsecurity/megalinter/assets/17500430/9c35edea-4461-47c7-bd5c-76f0792a552d)

Source of the schema, with nice article explaning it: https://www.deepfactor.io/security-scanning-tools-defined-sast-iac-sca-dast-iast-rasp-container-runtime-security-and-runtime-sca/

Runtime scan tools (DAST, Container security...)  is another wide topic with different behaviors, that on my opinion shouldn't be mixed with the "static analysis" scope of MegaLinter 🤓

Anyway, it's good to have such discussions between experts, i think it makes all of us progress 🎉

**Comment by wesley-dean-flexion** [comment]
> it's good to have such discussions between experts, i think it makes all of us progress

Well said.  I couldn't agree more.

> Thanks for reaching out. [...] Sorry this wasn't the answer you were hoping for.

No need to apologize!  Given the conversation, I'm inclined to agree fully with this model of what may or may not be a good linter / feature to add to MegaLinter.

Thank you for your time, energy, and thoughtful responses, all.
