### ISSUE TITLE
secretlint documentation bug re: no .secretlintignore file

### ISSUE THREAD

**Issue by KlfJoat** [oxsecurity/megalinter#3328]
**Describe the bug**
I was wondering about the behavior of `secretlint` and looked at #2992. It led me to see that there is a difference between implementation and documentation. 

The documentation at https://megalinter.io/latest/descriptors/repository_secretlint/ says:
> See [How to ignore files and directories with secretlint](https://github.com/secretlint/secretlint/blob/master/docs/configuration.md#secretlintignore)
> If custom `.secretlintignore` ignore file is not found, [`.secretlintignore`](https://github.com/oxsecurity/megalinter/tree/main/TEMPLATES/.secretlintignore) will be used

**Expected behavior**
To me, this implies that if I do not configure a `.secretlintignore` file, then a default one will be generated on the fly with the same contents as at that link, then the file will be discarded.

**Actual behavior**
However, [the actual code](https://github.com/oxsecurity/megalinter/blob/b2813b52bde3fb7c236ede8e64b257107a0c4a58/megalinter/linters/SecretLintLinter.py#L30) shows that if a custom `.secretlintignore` file is not found, then `.gitignore` will be used, not a default.

**Desired outcome**
Update the documentation to match the implementation.

**Comment by nvuillam** [comment]
Default .secreetlintignire that is shipped with MegaLinter image is not .gitignore but a default file containing `megalinter-reports` :)

https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.secretlintignore

**Comment by pjungermann** [comment]
@nvuillam As far as I got the description above and the code, the issue is that when I have no `.secretlintignore` locally, it will **not** use the default `.secretlintignore` shipped with the MegaLinter image/from the TEMPLATES dir but tries to use a local `.gitignore` instead.

The default `.secretlintignore` only contains
```
megalinter-reports
```
which is likely part of `.gitignore` files in repos anyway.
Also, using it would likely result in `.gitignore`-ed files not to be excluded anymore.

To me, it could make sense
- to adjust the documentation to state the actual behavior,
- and to remove the file from the `TEMPLATES/` dir.

**Comment by nvuillam** [comment]
@pjungermann sorry for the delay (very long days at work ^^)

I agree with your solution, would you like to make a PR ? :)

**Comment by pjungermann** [comment]
FYI: relates to #1207
