### ISSUE TITLE
Semgrep status in documentation

### ISSUE THREAD

**Issue by Jayllyz** [oxsecurity/megalinter#3372]
**Describe the bug**
According to the documentation, [semgrep](https://megalinter.io/latest/descriptors/repository_semgrep/) is currently disabled due to this issue https://github.com/semgrep/semgrep/issues/9632.
Looks like the issue is now resolved.

**Expected behavior**
Update the documentation and enable again semgrep (if that's not already the case)

**Comment by nvuillam** [comment]
@Jayllyz good catch :)

Would you like to do it in a PR ?  

https://github.com/oxsecurity/megalinter/blob/190cd0dad6dc52b2de5b810e3b290c3d6bdcc0f2/megalinter/descriptors/repository.megalinter-descriptor.yml#L387

You jsut have to remove the disabled text here, coz it seems SemGrep has been reenabled since the issue is fixed :)
