### ISSUE TITLE
How/where have to set the ssh key to clone roles using /roles/requirements.yml?

### ISSUE THREAD

**Issue by DaniPorras02** [oxsecurity/megalinter#3445]
Getting this error on github-actions workflow when running megalinter to a playbooks project with /roles/requirements.yml:

ERROR    [WARNING]: - role-name was NOT installed successfully: - command
/usr/bin/git clone git@github.com:compamny/role-name.git role-
name failed in directory /root/.ansible/tmp/ansible-
local(...) - Cloning into 'role-name'... Host
key verification failed.  fatal: Could not read from remote repository.  Please
make sure you have the correct access rights and the repository exists.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
 
The requirements.yml is using ssh to clone the roles

- Used SSH_KEY as env -> didn't work
- Used pre command to copy my .ssh/id_rsa to /root/.ssh inside the megalinter container -> didn't work
- Used key works in the regular environment

**Comment by alexanderbazhenoff** [comment]
1. Collections from GitLab or GitHub?
2. Can you provide a full content of your `requirements.yml`? (you can replace URLs if you wish keeping the structure).

> Used SSH_KEY as env -> didn't work
I am not sure that you really need a ssh connection to install your ansible collection(s), just because it works with [git via http(s)](https://stackoverflow.com/questions/55773505/where-to-place-requirements-yml-for-ansible-and-use-it-to-resolve-dependencies), not Ansible Galaxy.

If your roles are public you can publish them to [Ansible Galaxy](https://galaxy.ansible.com/ui/). Then you can install them using standard dependeicies, e.g.: `namespace.collection_name`. It's also [works](https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles) with a single roles.

If you still need to install using git, I believe you can put your [access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) in the URL: PAT [for GitHub](https://stackoverflow.com/questions/57780240/how-to-access-github-via-personal-access-token-in-url), or [PAT](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) for [GitLab](https://stackoverflow.com/questions/67514257/gitlab-personal-access-token-where-to-keep-the-token-for-seamless-clone-pull). You can also pass your personal access token to [env variables](https://stackoverflow.com/questions/71865215/using-pat-or-github-token-to-access-a-private-github-repository-with-a-subfolder) and [hide them](https://megalinter.io/latest/config-variables-security/) from logs.

The only thing I don't remember is [about using variables inside `requirements.yml`](https://github.com/ansible/ansible/issues/44374), but you can template them before linting using [pre-commands](https://megalinter.io/latest/configuration/) (also [`PRE_COMMANDS`](https://megalinter.io/latest/configuration/) env variable).

**Comment by nvuillam** [comment]
I never used ansible, but would a [pre-command](https://megalinter.io/latest/config-precommands/) work ?

Something like

```yaml
PRE_COMMANDS:
  - command: ansible-galaxy install -r requirements.yml
    cwd: "workspace"   # Will be run at the root of the workspace (usually your repository root)
    continue_if_failed: False  # Will stop the process if command is failed (return code > 0)
```
