### ISSUE TITLE
Detect smallest flavour to improve performance?

### ISSUE THREAD

**Issue by vonbraunbates** [oxsecurity/megalinter#3738]
Most of my actions mintues on a linter run are spent downloading the ~4GB Docker image.  There's no flavour I can use to reduce this.  Github Actions support suggests that I can cache the image, but how do I actually go about doing this?  Has anyone tried it before with a successful result?  Are there any arguments against doing this?

**Comment by echoix** [comment]
Last time I tried, I wasn't able to do anything for that. GitHub actions, when the action type is docker like ours, have the image pulled before starting, before running any step. Thus it can't work. But, if you drop the action and use the mega-linter-runner, like locally, you would be able to do something. If you think the actions cache server is faster than the docker server, you can try pulling from the ghcr registry where we upload it too. I expect it to be at the same level as the actions cache servers.

I'm sceptical that actions cache will really be faster, since it can only unpack once downloaded, and you still have to load the image to docker afterwards

**Comment by vonbraunbates** [comment]
@echoix in that case, the obvious next step is to have something in the action which decides on a flavour to pull dynamically.  E.g. if I have only changed `.sh` files, pull some flavour with all `SHELL` linters, instead of the entire image.  At the end of a (local) Megalinter run, I usually see a message saying that I could get better performance wand it spits out a list of flavours.  Where can I find the logic for this?  If I can implement the equivalent logic beforehand, at least this would minimise the size of the image to download.

**Comment by echoix** [comment]
https://github.com/oxsecurity/megalinter/blob/f9eed5e22e225df0a7fda67b2358f2f7e51ce36b/megalinter/flavor_factory.py#L128-L163

**Comment by echoix** [comment]
@vonbraunbates If ever your idea of refactoring includes having a base (no-op) image of only Megalinter logic and code (without the linters), it might be nice to refactor a bit the images and flavors we build to not have to install Megalinter (Python code+deps) like 100 times at each merge (full image, all the flavors, and the individual linters as docker images). That's a possibility.

And the other one is the one I thought of before, of using content-addressable images, but needs a proof of concept to make sure some gains are possible.

**Comment by nvuillam** [comment]
That is an interesting discussion, but would require some kind of "MegaLinter superlight" with zero embedded linters, that would be run first just to detect local files then compute the lightest flavor matching, then call again MegaLinter with the appropriate flavor

That's far from impossible, but would require to build this "MegaLinter superlight", and today MegaLinter own code is more like a monolith ^^
