### ISSUE TITLE
Display linters' command in logs

### ISSUE THREAD

**Issue by VictorRos** [oxsecurity/megalinter#4205]
**Is your feature request related to a problem? Please describe.**

Not directly.

**Describe the solution you'd like**

In `MegaLinter` logs, for each **linter** I would like to have the linter command run by `MegaLinter`

**Describe alternatives you've considered**

**Additional context**

With recent `trivy` problems, we are trying to set up a workaround for our repositories that use MegaLinter prior to `8.1.0`.

I tried to set `trivy` environment variables (`TRIVY_*`) or adding `trivy` command options to download the database vulnerability but it still try to download it from GHCR registry instead of AWS registry I set up.

So I would like to see the command MegaLinter is using when calling `trivy`.

It could be useful to see all linters commands in logs so we know what options are set by our configuration or the default MegaLinter configuration.

What are your though about that?
Is there already a way to display them?

**Comment by echoix** [comment]
Set the env var `LOG_LEVEL` to `DEBUG`. It should to it https://megalinter.io/latest/config-variables/

**Comment by nvuillam** [comment]
@VictorRos after thinking about your request... I agree that with the huge logs generated by LOG_LEVEL: DEBUG, it can be good to see the command everytime, at least for educational purposes :)

I truncated the command to the first 250 chars because for the linters who use a list of files as argument, it would have been very long logs, and there is no added value to see all the files, it's the arguments before that are important :)

Thanks for suggestion the update :)
