### ISSUE TITLE
Conflicting file types: both Dockerfile and Markdown

### ISSUE THREAD

**Issue by gautaz** [oxsecurity/megalinter#4324]
**Describe the bug**
Hello,

We have the habit in our projects to document each file with a Markdown file next to it.
The name of the Markdown file is the same as the file it documents with an added .md extension.
Hence when a project contains a file named Dockerfile, it also contains a file named Dockerfile.md next to it.

While trying megalinter, I have found out that it considers a file named Dockerfile.md as both:

- a Dockerfile file (I guess because it starts with the prefix Dockerfile)
- a Markdown file (because it ends with the suffix .md)

This means in particular that megalinter will ask checkov to scan the file.
I did not find a simple way for now to avoid checkov scanning files with names ending with the suffix .md.
As soon as a file is considered to be of a certain type, shouldn't megalinter try to avoid applying other types of scanners to it?
There is also the matter of which order (Markdown first or Dockerfile first) to apply if such a mechanism is implemented.

**To Reproduce**

1. create a project with a Markdown file named Dockerfile.md
2. try megalinter on the newly created project

**Expected behavior**
I would expect that Markdown files are not also detected as Dockerfile files.

**Screenshots**
N/A

**Additional context**
None

**Comment by echoix** [comment]
I assume this is a similar question to https://github.com/super-linter/super-linter/issues/6410

I think that what you're fighting against is the configuration of the tool itself, or a limitation in the tool itself. Checkov is designed to generally run on folders or the whole project, as in some environments supported by checkov, it doesn't make sense otherwise. For Dockerfiles, I agree it would make sense to treat it by file instead. Then it could be configured normally like in https://megalinter.io/v8/descriptors/repository_checkov/ and for file filtering, as https://megalinter.io/v8/config-filtering/. As noted there, file filtering doesn't make sense for tools that are used with a single call per project, as used by default.

If you are able to write down the exact command, options, or configuration file that you can use locally to directly use the tool the way you expect, let us know here and we can try to help you transposing it to a megalinter configuration.


If you struggle too much, try looking for existing info or issues, and then asking help on the checkov side, you might have better luck there.

**Comment by gautaz** [comment]
Hello @echoix,

> I assume this is a similar question to super-linter/super-linter#6410

Yes, I am trying different solutions to find the one that best fits our use cases.

> As noted there, file filtering doesn't make sense for tools that are used with a single call per project, as used by default.

I didn't realize at first that the way the different scanners were fed would depend on the scanner.
So now it makes more sense that it is quite difficult for MegaLinter (and super-linter) to manage the different types of incompatibilities between all these tools depending on each project organization.

Looking at the documentation you've pointed out, I was in fact able to cope with our particular use case by simply declaring:

```yaml
REPOSITORY_CHECKOV_ARGUMENTS: '--skip-path ".*\.md"'
```

Thank you for your input, I'm closing the issue.

**Comment by echoix** [comment]
I'm glad it was useful for you! Indeed, working to reconcile different tool and their sometimes conflicting paradigms is what we try to solve. We may not be experts on each tool, but have a global view in between tools ;)
