### ISSUE TITLE
Support for GitLab "Code Quality" artifacts

### ISSUE THREAD

**Issue by DarwinJS** [oxsecurity/megalinter#539]
**Is your feature request related to a problem? Please describe.**
Any tool can integrate with GitLab Code Quality - including visual display in the MR widget - by simply outputting a correctly formatted artifact file. The benefits are here: https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

**Describe the solution you'd like**
Implement a command line that allows GitLab's code quality artifact to be emitted.  GitLab's format is based on the CodeClimate format - so this may also allow the format to be consumed by any tool that supports the Code Climate format.

Instructions are here: https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool

**Describe alternatives you've considered**
Text artifacts and JUNIT as proposed in #538 

**Additional context**

**Comment by nvuillam** [comment]
There is a [current PR](https://github.com/nvuillam/mega-linter/pull/377) including ReviewDog, would that cover the requirement ?

**Comment by haydenseitz** [comment]
I would also love to see Gitlab Code Quality integration!

> There is a [current PR](https://github.com/nvuillam/mega-linter/pull/377) including ReviewDog, would that cover the requirement ?

According to the Gitlab docs, Code Quality reports use a similar format to [Code Climate](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types). I don't think the JSONL work in that other PR would work for Gitlab.

**Comment by nvuillam** [comment]
@haydenseitz there is a current PR about Gitlab integration, but just in comments for now

About Gitlab code quality reports... I don't know CodeClimate format, is it far from SARIF format ? ( because the v6 version that we are preparing will support SARIF output ^^ )

**Comment by gmeligio** [comment]
I'm interested in this too and found this [SARIF to CodeClimate converter](https://www.npmjs.com/package/sarif-codeclimate) that was created for this [Gitlab template](https://www.npmjs.com/package/sarif-codeclimate). I haven't tested yet though.

**Comment by nvuillam** [comment]
@gmeligio sarif-codeclimate has been built for MegaLinter integration by @GridexX from @r2devops

You can have a look to Gitlab tab of MegaLinter job on R2DevOps -> https://r2devops.io/_/r2devops-bot/mega_linter

I've not validated the job yet, but it's possible it will work at first try :)

If you build a script with working codeclimate format upload to Gitlab, please share it here :)

**Comment by gmeligio** [comment]
@nvuillam thank you for sharing the link. I meant to comment on this [Gitlab template link](https://gitlab.com/r2devops/hub/-/blob/latest/jobs/mega_linter/mega_linter.yml) from the repo but repeated the NPM link. I corrected it in my previous comment. That is the source code of the Gitlab tab you shared. I prefer to use it as `remote: 'https://gitlab.com/r2devops/hub/-/blob/latest/jobs/mega_linter/mega_linter.yml'` than from the r2devops API.

I tested a bit today but it took an hour to run with that template's default configuration. I have to disable some linters I don't need. I haven't gotten to the point of a successful job, so the Code Quality report doesn't show yet. I will continue testing later next week. and comment here on my results.

**Comment by Totara-thib** [comment]
> 
Hello @gmeligio
I will do additional tests on the https://r2devops.io/_/r2devops-bot/mega_linter job to ensure the `Code Quality` report is properly shown.

Could you also tell me why you prefer to use the repository link instead of the R2Devops API?

I will keep you in touch if everything works as expected on this job and if that's the case i could give you an hand to make it succeed on your project.

**Comment by gmeligio** [comment]
Hi. I did some tests today until I got some output. I ran the `megalint-security` flavour only to have fast results.

I got it working in GitLab branch pipelines, not MR pipelines, but I think it should be very similar because the report is uploaded successfully.

I had some issues that were resolved and opened an MR upstream https://gitlab.com/r2devops/hub/-/merge_requests/422

I usually use the YAML directly or even only copy the relevant parts to have fewer dependencies, like unexpected template updates, website downtime, etc. Because I don't have tests for the pipeline, I check more carefully what I put there. I will read more about what the API provides and see if I can use it.

**Comment by Totara-thib** [comment]
> I had some issues that were resolved and opened an MR upstream https://gitlab.com/r2devops/hub/-/merge_requests/422

Thank you for your feedback, we will take a look at changes and enforce the job accordingly.

**Comment by Totara-thib** [comment]
The issue have been fixed by @gmeligio on the R2Devops job https://r2devops.io/_/r2devops-bot/mega_linter in this merge_request https://gitlab.com/r2devops/hub/-/merge_requests/422

Just a last quick note to @gmeligio :

Be careful while using the latest version of a remote job: 
`remote: 'https://gitlab.com/r2devops/hub/-/blob/latest/jobs/mega_linter/mega_linter.yml'`
Because the behavior of the job could change on the latest version but it won't be the case on a fixed version.
